### ISSUE TITLE
Local time?

### ISSUE THREAD

**Issue by binarykitchen** [trentm/node-bunyan#103]
Hi there

If I want to log with the local time instead of UTC, what is the easiest way to reconfigure that through options? That information seems to be missing in the README ...

**Comment by arg20** [comment]
+1, I see the data in UTC but I live in UTC-3 so I have to do a bit of math for every entry I see, which can get annoying. I want to store the data in UTC, but I just would like to display it in UTC-3

**Comment by trentm** [comment]
@yicone Thanks for showing some code!

This'll be in bunyan 1.3.0 when I release that (soonish). Cheers.

**Comment by binarykitchen** [comment]
@trentm coooool, so what now? what configuration changes are needed to show up local times?

**Comment by trentm** [comment]
@binarykitchen Per the discussion above it is just for the rendered "pretty" output that the `bunyan` CLI provides. Use the `-L` option..

**Comment by binarykitchen** [comment]
ok, thx!

**Comment by arg20** [comment]
Just a quick question, can the cli tool use the TZ environment variable that node uses? This scenario happens to me all the time:

Server in cloud: UTC - 5
Dates stored in: UTC
Client from which we log in: UTC -3

If it uses the timezone in the server, if we uploaded to a server say in amazon, but we are from any other country, we will get the dates with amazon's timezone. Can we somehow specify which timezone we want? Or set TZ env variable for that matter?

**Comment by trentm** [comment]
@arg20: Unintentionally yes it does, at least for me:

```
$ cat foo.log  | ./bin/bunyan
[2015-01-26T06:06:31.747Z]  INFO: foo/68824 on grape.local: hi
$ cat foo.log  | ./bin/bunyan -L
[2015-01-25T22:06:31.747Z]  INFO: foo/68824 on grape.local: hi
$ cat foo.log  | TZ=GMT-5 ./bin/bunyan -L
[2015-01-26T11:06:31.747Z]  INFO: foo/68824 on grape.local: hi
$ cat foo.log  | TZ=GMT-4 ./bin/bunyan -L
[2015-01-26T10:06:31.747Z]  INFO: foo/68824 on grape.local: hi
```

This is the function being used (docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset):

```
$ node -e 'console.log((new Date()).getTimezoneOffset())'
480
$ TZ=EST+5  node -e 'console.log((new Date()).getTimezoneOffset())'
300
```

**Comment by arg20** [comment]
@trentm Great! (Sorry I just got to read this), then it's perfect for me.

**Comment by chaosforfun** [comment]
+1 local time is necessary for read

**Comment by jcollum** [comment]
YSK that `-L` is not working in the 1.8.0 version. [Bug report entered here](https://github.com/trentm/node-bunyan/issues/373). Unless I'm doing something wrong that I don't see.

**Comment by mohammadranjbar** [comment]
I forked bunyan to show local time in logs, you can use that when piping logs 

https://github.com/mohammadranjbar/node-bunyan
(You can pass time moment format in environment variable to show with your time format)

`npm i -g bunyan-adanic`
`cat foo.log  | ./bin/bunyan-adanic`

**Comment by OhnkytaBlabdey** [comment]
does rotating file supports local time now?

**Comment by haidarabdillah** [comment]
seem still not solved?

**Comment by dasbts** [comment]
> seem still not solved?

I FINALLY managed to solve it like this: 
```
const bunyan = require('bunyan');

const formatter = new Intl.DateTimeFormat('sv-SE', {
  day: '2-digit',
  hour: '2-digit',
  hour12: false,
  minute: '2-digit',
  month: '2-digit',
  second: '2-digit',
  timeZone: 'Europe/Stockholm',
  year: 'numeric' // ensures correct timezone
});

// Helper function to format to "YYYY-MM-DD HH:mm:ss"
function format(date = new Date()) {
  const parts = formatter.formatToParts(date);
  const lookup = {};
  parts.forEach(p => {
    lookup[p.type] = p.value;
  });

  return `${lookup.year}-${lookup.month}-${lookup.day} ${lookup.hour}:${lookup.minute}:${lookup.second}`;
}

// Monkey-patching bunyan to print local time in the logs...
// eslint-disable-next-line no-underscore-dangle
const originalEmit = bunyan.prototype._emit;
function patchedEmit(rec, noemit) {
  const patchedRec = {
    ...rec,
    time: format(new Date())
  };
  return originalEmit.call(this, patchedRec, noemit);
}
// eslint-disable-next-line no-underscore-dangle
bunyan.prototype._emit = patchedEmit;
```

Change to your preferred in the const formatter
