### ISSUE TITLE
cluster + rotating file + large log file = crash

### ISSUE THREAD

**Issue by 2fours** [trentm/node-bunyan#117]
Running on linux...see this in my journal at exactly midnight: 

Dec 19 17:00:00 surespot-node-2 coffee[19539]: events.js:72
Dec 19 17:00:00 surespot-node-2 coffee[19539]: events.js:72
Dec 19 17:00:00 surespot-node-2 coffee[19539]: throw er; // Unhandled 'error' event
Dec 19 17:00:00 surespot-node-2 coffee[19539]: ^
Dec 19 17:00:00 surespot-node-2 coffee[19539]: throw er; // Unhandled 'error' event
Dec 19 17:00:00 surespot-node-2 coffee[19539]: Error: ENOENT, rename 'logs/surespot.log'
Dec 19 17:00:00 surespot-node-2 coffee[19539]: ^
Dec 19 17:00:00 surespot-node-2 coffee[19539]: Error: ENOENT, rename 'logs/surespot.log'

The log files now look like this: 

-rw-r--r-- 1 surespot users 10966716 Dec 19 16:59 surespot.log.2
-rw-r--r-- 1 surespot users        0 Dec 19 17:00 surespot.log.0
-rw-r--r-- 1 surespot users 58868418 Dec 20 08:11 surespot.log

**Comment by halt-hammerzeit** [comment]
What about using a specific `Log` in workers which sends the messages to the master via some kind of `IPC`.
And then there will be a single log file.
And noone will be forced to rely on 3rd party tools like `logrotate`

**Comment by mihir83in** [comment]
Why is this closed on winstonjs link ?
