### ISSUE TITLE
bunyan-cli should ignore SIGINT when processing stdin from pipe.

### ISSUE THREAD

**Issue by timborodin** [trentm/node-bunyan#126]
Steps to reproduce (mac here):
test.js

``` javscript
var bunyan = require('bunyan');
var log = bunyan.createLogger({name: 'test'});

var timeout = setTimeout(function () {}, 10000);

process.on('SIGINT', function () {
    log.info('SIGINT here!');
    clearTimeout(timeout);
});
```

Run with, and hit ctrl+C in a second to send SIGINT:

```
node test.js | bunyan
```

Output:

```
node test.js | bunyan
^C
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)
```

Cause seems to be pretty obvious:
1. SIGINT is sent to all process in a process group.
2. bunyan(-cli) process exists.
3. test.js app tries to log to stdout and fails, because other side of a pipe is closed.

Suggested solutions:
bunyan-cli is purposed to analyse logs post-factum or realtime.
It should not react to SIGINT when processing stdin.
It should expect process on the left of '|' to terminate and process all it's output.
After process on the left of '|' terminates bunyan-cli will correctly terminate after receiving EOF from stdin.

I checked it adding a quick and dirty hack to bunyan:

```
global_processing_stdin = false;

function processStdin(opts, stylize, callback) {
    global_processing_stdin = true;
        ...
```

and

```
function cleanupAndExit(code, signal) {
    // Guard one call.
    if (cleanedUp || global_processing_stdin) {
        return;
    }
    ...
```

**Comment by trentm** [comment]
reverted in bunyan@1.8.9, see discussion in #246
