### ISSUE TITLE
install still fails on osx with 0.11.x

### ISSUE THREAD

**Issue by Ognian** [trentm/node-bunyan#135]
The problem is with compiling of dtrace-provider (node-dtrace-provider).
There is already a pull request with a changed build using nan , but it looks like it is not merged since 4 months now...
So my suggestion would be if you could make the whole dtrace thing optional so that dtrace-provider should be required separately ?
That would help a lot
Thanks
Ognian

**Comment by bjm88** [comment]
I'm still seeing this issue
npm install bunyan

Building dtrace-provider failed with exit code 1 and signal 0

node -v
v4.2.1

npm -v
2.14.7

Mac OS x 10.10.5
Darwin  14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
