### ISSUE TITLE
Trace-level and rotating file problem (empty file)

### ISSUE THREAD

**Issue by whoisvolos** [trentm/node-bunyan#171]
Good day everyone!
I want to _trace_ my webapp metrics to log file (OS X 10.9):

```javajscript
var logger = bunyan.createLogger({
    name: "some-project-tracer",
    level: "trace",
    streams: [{
      type: "rotating-file",
      path: "/var/log/some-project/trace.log",
      period: "1d",
      count: 7
    }]
  });

logger.trace({ metrics: { requests: 0 } });
```

Result: file has been created but it's empty. If I use _logger.info_ instead of _logger.trace_ it works, but I've set "trace" level in logger parameters. I had read levels section but haven't found anything special about _trace_ function.

**Comment by Bloutiouf** [comment]
By default, bunyan does not output debug and trace levels. You need to call

    logger.level('trace');

**Comment by trentm** [comment]
Sergey,

The changelog for bunyan 1.3.1 has this:

```
## bunyan 1.3.1
...
- [issue #164] Ensure a top-level `level` given in `bunyan.createLogger`
  is *used* for given `streams`. For example, ensure that the following
  results in the stream having a DEBUG level:

        var log = bunyan.createLogger({
            name: 'foo',
            level: 'debug',
            streams: [
                {
                    path: '/var/tmp/foo.log'
                }
            ]
        });

  This was broken in the 1.0.1 release. Between that release and 1.3.0
  the "/var/tmp/foo.log" stream would be at the INFO level (Bunyan's
  default level).
```

which I think it what you want to get what you expect there. What version
of bunyan are you using?

Cheers,
Trent


On Thu, Oct 9, 2014 at 6:57 AM, Sergey Golubev <notifications@github.com>
wrote:

> Good day everyone!
> I want to *trace* my webapp metrics to log file (OS X 10.9):
>
> var logger = bunyan.createLogger({
>     name: "some-project-tracer",
>     level: "trace",
>     streams: [{
>       type: "rotating-file",
>       path: "/var/log/some-project/trace.log",
>       period: "1d",
>       count: 7
>     }]
>   });
>
> logger.trace({ metrics: { requests: 0 } });
>
> Result: file has been created but it's empty. If I use *logger.info
> <http://logger.info>* instead of *logger.trace* it works, but I've set
> "trace" level in logger parameters. I had read levels section but haven't
> found anything special about *trace* function.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trentm/node-bunyan/issues/171>.
>



-- 
Trent Mick
