### ISSUE TITLE
Mute log record emission through Environment Variables

### ISSUE THREAD

**Issue by marcellodesales** [trentm/node-bunyan#175]
Hi there,

I was looking for a way to disable a given record to be emitted depending on its value. Is this possible???

My requirement is as follows:

Component A
- require("bunyan");

Component B
- Is composed by Component A
- require("bunyan");

Components A and B have their own logging settings. Considering Component A is a shared library, I want to be able to disable records to be logged from Component B, depending on the properties of the logs from Component A, say, "component".

I'm thinking about something like this... Given the record:

```
{ name: "my app",
   component: "componentA"
   ...
}
```

I want to be able to remove disable the logging specifically from this using environment variables on Component B like the one below:
 
```
{{{
process.env.BUNYAN_DISABLE_REC_component = "ComponentA".
}}}
```

thanks!
Marcello

**Comment by trentm** [comment]
Thanks for the issue. See my comments on #176.
