### ISSUE TITLE
How to remove hostname and pid from logs?

### ISSUE THREAD

**Issue by binarykitchen** [trentm/node-bunyan#187]
Just wondering. I do not these information in my logs and would like to "pollute" my logs with less data. Thanks!

**Comment by trentm** [comment]
@binarykitchen Regarding documenting this: I'd welcome a "Bunyan Hacks" wiki page edited by others, if you wanted to start one? hint ;)  The current Bunyan README.md is getting a little long in the tooth.

Deleting 'v': Given that I tried to set a base "spec" for what fields are included in a bunyan log record I just didn't design for any of these fields being hacked out. `rec.v` is just assigned late in `mkRecord` so you can't strip it out in the same way. I don't have a good suggestion right now for stripping that, other than having your stream(s) be a 'raw' stream that handles stripping the 'v' field and then writing it to file/output-stream/wherever.

**Comment by binarykitchen** [comment]
Bummer that `v` cannot be stripped out. Shall I create a new, low-priority ticket for that?

I'll consider writing a Bunyan Hack Wiki when I have time. But not now, sorry ...

**Comment by trentm** [comment]
For stripping 'v', I think I'd push that out until 2.x work to streamify bunyan logging more nicely s.t. it would hopefully be trivial to have a filter on bunyan streams that did the stripping you want.  Sure on the ticket. :)

**Comment by bochen2014** [comment]
most people just want a tool to easily control log levels, there is no point of having those `name`, `hostname`, `pid`, `v` ... in my log; 

there is only one name, one hostname, one pid, so doesn't make things to make them mandatory

**Comment by joac** [comment]
After dealing with an issue on a monitoring system caused by the domain field, I simply moved all logging to winston and called it a day.
