### ISSUE TITLE
Setting log level for all children

### ISSUE THREAD

**Issue by borisovg** [trentm/node-bunyan#188]
Is it possible to set the log level of all children at once? (Assuming access to the main logger object.)

I am using a separate child logger for each module in my application and I would like to have a way to modify the level on all of these loggers at once (e.g. set them all to debug when troubleshooting an issue).

The modules are quite independent and are only aware of each other on a need-to-know basis.

**Comment by gautaz** [comment]
**Warning: self-promotion :-)**

For the record, I also had the same need to set log levels recursively.

Following what @borisovg said, a npm package is available and fulfills the need of recursive calls (not only log levels) on buyan childs: https://www.npmjs.com/package/bunyan-tree

It still needs refining and more testing...
