### ISSUE TITLE
Emit levels in STRING instead of integers

### ISSUE THREAD

**Issue by marcellodesales** [trentm/node-bunyan#194]
Hi there,

Is there any support to emitting the records as STRING values instead of integers??? We use Splunk to aggregate the logs without any pre-processing step like logstash... Splunk indexes json events and our requirement is to print the String representation to be aligned with other systems...

The requirement is that the console output must be using the "bunyan" format, while the console.log format is the "long", human-readable one... This requirement is only when writing to the rotate-file stream type... 

From
===

* level: 20

```
{...,"level":20,"msg":"Missing property 'logs.file.dir'....}
```

To
===

* level: ERROR

```
{...,"level":ERROR,"msg":"Missing property 'logs.file.dir'....}
```

I found the method `_emit` (https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L778), but it is emitting for all the types :( Any help greatly appreciated!

thanks
Marcello

**Comment by trentm** [comment]
@marcellodesales I got it working here: https://gist.github.com/trentm/8f16f630ddd73d3f87d4

*Not* in bunyan core, but it *does* require a change to bunyan to export the `RotatingFileStream` class, which I've done in commit b9e3a0d. Note that this is a bit inefficient in that it does the `JSON.stringify` again (internally Bunyan will already be doing this in its `_emit`).

I don't think I want explicit support for this in Bunyan core because it would basically mean an option that results in emiting log records that are *almost* Bunyan-spec'd log records, but not quite.  That said, it is very laborious to customize a stream to do something like this. I hope that with Bunyan 2.x plans (no timeline for that at all) to make bunyan stream handling a lot cleaner, it would be easy to compose the built in rotating file stream and a small object stream that did the `level` translation.

Please re-open if I missed something.

**Comment by olsonpm** [comment]
I understand not modifying the current bunyan codebase to cater this use-case, however I do suggest modifying the structure in 2.x to resemble a difference as noted in the following:

```
// from
var TRACE = 10;
var DEBUG = 20;
//...

var levelFromName = {
    'trace': TRACE,
    'debug': DEBUG,
    //...
};


// to
function LogLevel(name_, level_) {
  this.name = name_;
  this.level = level_;
}
var LogLevels = [];
LogLevels.push(new LogLevel('trace', 10));
// etc...

module.exports.LogLevel = LogLevel
module.exports.LogLevels = LogLevels;
```
Poor naming aside, this would future-proof that portion of the code as well as make it more cohesive.  Any helper functions could just be prototyped onto LogLevel by developers wanting to extend its functionality and prevent little utility helper functions from needing to exist.

**Comment by marcellodesales** [comment]
@trentm Thanks for adding an example... However, it would be great to not only export `RotatingFileStream`, but also `ConsoleRawStream`... Our deployments output to console because we deploy using Docker and/or Upstart...

thanks!

**Comment by c24w** [comment]
I know this is an ancient issue, but for anyone landing here: you can just use `bunyan.nameFromLevel` to figure out the name from the level number.

**Comment by ghostganz** [comment]
Still can't actually change the output of the 'level' field to a string though?

Thinking about how to post-process the output, or switching to some other lib.

**Comment by c24w** [comment]
I don't think so - we ended up doing something like this:

```js
function wrappedRedisTransport() {
  const rt = new RedisTransport({ /* ... */ });

  return {
    write: entry => rt.write(Object.assign(entry, {
      level: bunyan.nameFromLevel[entry.level]
    }))
  };
}

bunyan.createLogger({
  streams: [{
    type: 'raw',
    stream: wrappedRedisTransport()
  }]
});
```

**Comment by emertechie** [comment]
For the benefit of anyone else trying to log string levels to file, here's what I came up with:

```js
function sensibleFileStream(filePath) {
    const fileStream = fs.createWriteStream(filePath, {
        flags: 'a',
        encoding: 'utf8'
    });
    return {
        write: log => {

            // Map int log level to string
            const clonedLog = Object.assign(log, {
                level: bunyan.nameFromLevel[log.level]
            });

            // remove bunyan format version:
            delete clonedLog.v;

            var logLine = JSON.stringify(clonedLog, bunyan.safeCycles()) + '\n';
            fileStream.write(logLine);
        }
    };
}
```

Don't forget to set the type to raw when you use it:

```js
bunyan.createLogger({
  streams: [{
    type: 'raw',
    stream: sensibleFileStream('/path/to/file')
  }]
});
```

**Comment by darrelcox** [comment]
Here's what I came up with....

`
function myStdOutWithLevelName() {}
myStdOutWithLevelName.prototype.write = function(data) {
    var logObject = JSON.parse(data)
    
    // Change log level number to name and write it out
    logObject.level = bunyan.nameFromLevel[logObject.level]
    process.stdout.write(JSON.stringify(logObject) + '\n')
}
}
`

**Comment by darrelcox** [comment]
Here's what I came up with....

```
function myStdOutWithLevelName() {}
myStdOutWithLevelName.prototype.write = function(data) {
    var logObject = JSON.parse(data)

    // Change log level number to name and write it out
    logObject.level = bunyan.nameFromLevel[logObject.level]
    process.stdout.write(JSON.stringify(logObject) + '\n')
}
```

```
bunyan.createLogger({
    name: "console",
    streams: [
        {
            level: "trace",
            stream: new myStdOutWithLevelName()
        }
    ],
    src: false,
    serializers: bunyan.stdSerializers
})
```

**Comment by bfelbo** [comment]
Why doesn't this work when just using a serializer?

E.g.
```
let logger = bunyan.createLogger({
  name: "console",
  streams: [{
    stream: process.stdout,
    level: "trace",
    serializers: {
      level: function level(val){
        return bunyan.nameFromLevel[val]
      }
    }
  }]
})
```

**Comment by autocorrectoff** [comment]
how can I kick out some fields? 'v', for example

**Comment by lukesiler** [comment]
Combined a couple of hints here to be

```
function wrappedStdout() {
    return {
        write: entry => {
            // to simplify StackDriver UX, use severity and timestamp fields
            var logObject = JSON.parse(entry)
            logObject.severity = bunyan.nameFromLevel[logObject.level].toUpperCase();
            logObject.timestamp = logObject.time;
            delete logObject.time;
            process.stdout.write(JSON.stringify(logObject) + '\n');
        }
    };
}

const logger = bunyan.createLogger({
        name: loggerName,
        streams: [
            {
                level: logLevel,
                stream: wrappedStdout()
            }
        ]
    });
```
