### ISSUE TITLE
Build browser version of bunyan with browserify using "browser" field in package.json

### ISSUE THREAD

**Issue by pragmadash** [trentm/node-bunyan#195]
In browserify [documentation](https://github.com/substack/node-browserify#browser-field) it is described that best practice is build browser version of package using `browser` field in `package.json`.

Maybe it is better to separate files with server and browser-specific code and replace it on build using this field?

**Comment by trentm** [comment]
Thanks for the note. I considered that separation when adding browserify support, but it seemed a lot easier to just have the small amount of code in bunyan.js itself. Unless I hear that that *breaks* usage, I'll stick with the current implementation.
