### ISSUE TITLE
Colors disappear from output when piping through bunyan

### ISSUE THREAD

**Issue by raine** [trentm/node-bunyan#202]
![2014-12-23 16-51-42](https://cloud.githubusercontent.com/assets/11027/5538962/1669f258-8ac4-11e4-85b5-b29c014e5939.png)

```js
#!/usr/bin/env node
console.log(require('chalk').red('foo'));
```

bunyan's colors are printed correctly

**Comment by axelhzf** [comment]
chalk uses https://github.com/sindresorhus/supports-color to enable or disable colors.
You can pass a `--color` flag to force colors https://github.com/sindresorhus/supports-color/blob/master/index.js#L11

Alternatively you can enable it directly via code

```js
#!/usr/bin/env node
var chalk = require('chalk');
chalk.enabled = true;
console.log(chalk.red('foo'));
```

**Comment by trentm** [comment]
So, iiuc, not a bunyan issue.

**Comment by f03lipe** [comment]
For those using `colors.js` instead of chalk, see this https://github.com/Marak/colors.js/issues/125.

**Comment by soswow** [comment]
I recommend having it in readme.
