### ISSUE TITLE
Provinding count as a string (as opposed to integer) in rotating-file stream definition gives an obscure error

### ISSUE THREAD

**Issue by notnarb** [trentm/node-bunyan#207]
## report
When using the code snippet below, the program aborts with an
> AssertionError: false == true ...

when the issue appears to be that the 'count' value is a string rather than the expected type of integer.  It would be nice if the code checked the type of the 'count' field and either:
* called parseInt if it was a string or
* threw a more clear error since the current error is not very useful

## extra info

Node version
> node --version
> v0.10.25

Error: 

> assert.js:92
> throw new assert.AssertionError({
> ^
> AssertionError: false == true
> at new RotatingFileStream (/<app folder>/node_modules/bunyan/lib/bunyan.js:1029:12)
> at Logger.addStream (/<app folder>/node_modules/bunyan/lib/bunyan.js:502:20)
> at /<app folder>/node_modules/bunyan/lib/bunyan.js:370:18
> at Array.forEach (native)
> at new Logger (/<app folder>/node_modules/bunyan/lib/bunyan.js:368:25)
> at Function.createLogger (/<app folder>/node_modules/bunyan/lib/bunyan.js:1349:12)
> at Object.module.exports.init (/<app folder>/app/js/<bunyan requirer>.js:22:19)
> at Object.<anonymous> (/<app folder>/app/index.js:349:10)
> at Module._compile (module.js:456:26)
> at Object.Module._extensions..js (module.js:474:10)

Offending code: 
> var log = bunyan.createLogger({
>     name: 'foo',
>     streams: [{
>         type   : 'rotating-file',
>         path   : path.join(sqlLoggerPath, 'foo.log'),
>         count  : '15',
>         period : '1d'
>     }]
> });

**Comment by trentm** [comment]
Thanks! Fixed above witha better assert.
