### ISSUE TITLE
Your example has a syntax error, add the comma after TRACE: 'TRACE'

### ISSUE THREAD

**Issue by bitplanets** [trentm/node-bunyan#209]
var nameFromLevel = {
        TRACE: 'TRACE'
        DEBUG: 'DEBUG',
        INFO: 'INFO',
        WARN: 'WARN',
        ERROR: 'ERROR',
        FATAL: 'FATAL'
    };

**Comment by trentm** [comment]
Obsoleted by https://github.com/trentm/node-bunyan/issues/210. Thanks.
