### ISSUE TITLE
The output of the example is not correct

### ISSUE THREAD

**Issue by bitplanets** [trentm/node-bunyan#210]
Here is my output

    [Wed Jan 14 2015 11:29:52 GMT+0000 (Hora padrão de GMT)] undefined: hi on info

rec.level on my machine is === 30, not a string. Like here https://github.com/trentm/node-bunyan#levels

Fixed example

    function BunyanStream() {}
    BunyanStream.prototype.write = function (rec) {
        var nameFromLevel = {
            10 : 'TRACE',
            20 : 'DEBUG',
            30 : 'INFO',
            40 : 'WARN',
            50 : 'ERROR',
            60 : 'FATAL'
        };
        console.log('[%s] %s: %s', rec.time, nameFromLevel[rec.level], rec.msg);
    }

**Comment by trentm** [comment]
@bitplanets I don't know what example you are referring to.

**Comment by trentm** [comment]
oh, I see. Fixed in commit 7c0b566e639ce7188ab47db5cd4c5269263a24d9.  Thanks.
