### ISSUE TITLE
haveNonRawStreams not reset by addStream

### ISSUE THREAD

**Issue by msamblanet** [trentm/node-bunyan#218]
If you dynamically add a stream to a logger using addStream, it does not reset haveNonRawStreams. The result is if previously you only had raw streams, undefined is written to the new stream.

Work around is to add this after each call to addStream: logger.haveNonRawStreams = undefined;

but would be nice if the logger did it automatically

**Comment by trentm** [comment]
Thanks! This'll be in the next release.
