### ISSUE TITLE
RotatingFileStream not defined in firefox 35.0.1 ubuntu 14.10

### ISSUE THREAD

**Issue by olsonpm** [trentm/node-bunyan#223]
Here is the problematic code

https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L1089-L1091

I don't have time for a proper fix, but I just know you aren't supposed to conditionally define constructor functions.  It causes an error in firefox upon the module.exports declaration anyway.

Because I don't need rotatingfilestream for my personal project, I'm going to delete that code as a forked workaround.

**Comment by airtonix** [comment]
this line also causes problems: https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L1429

**Comment by llambda** [comment]
I can confirm this issue too, FireFox only, works in Safari and Chrome.

**Comment by trentm** [comment]
Should be fixed in v1.5.0. Sorry for my delays.

**Comment by olsonpm** [comment]
Much apprecated
