### ISSUE TITLE
RotatingFileStream is undefined in `strict` mode

### ISSUE THREAD

**Issue by sudhakar** [trentm/node-bunyan#231]
I am trying to use RotatingFileStream as one of the streams in the new project. Since RotatingFileStream is defined inside the ```if(mv)``` conditional, it is getting ```undefined``` even if  ```mv``` is available when used in ```strict``` mode.

Note that I need to enable ```strict``` mode globally by using ```--use_strict``` v8 flag (this is required for classes & block level support)

Instead of hiding the whole function definition inside ```if```(which gets hoisted & removed in strict mode), I propose changing the visibility using module exports 
```js
if(mv) {
  module.exports.RotatingFileStream = RotatingFileStream;
}
```

**Comment by trentm** [comment]
Should be fixed in v1.5.0.
