### ISSUE TITLE
Log API: How to separate the summary and detail text?

### ISSUE THREAD

**Issue by myndzi** [trentm/node-bunyan#237]
I'm trying to do something like this:

    log.info('Message', {
        // json data
    });

And I want the result to be something like this:

    {
        msg: 'Message',
        // don't really care how the rest is separated out
    }

But I'm observing that in the output, I get the message squashed into the json data without a newline or anything: `'Message { json data }'`

I've tried using something like this:

    log.info({
        msg: 'Message',
        detail: {
            // json data
        }
    });

But when I do that, 'msg' is blank for some unknown reason. I've looked at the docs but they don't seem to be clear on how to deal with this scenario, but you can see that logging say, an Error object, produces precisely the behavior I want. How can I do this with arbitrary data?

**Comment by jburnham** [comment]
The [api](https://github.com/trentm/node-bunyan/blob/master/README.md#log-method-api) says you need to pass the object you want to serialize as the first argument and then you can specify a message. Try this:

```
log.info({
    // json data
}, 'Message');
```

This will output
```
{
    msg: 'Message',
    // don't really care how the rest is separated out
}
```

**Comment by myndzi** [comment]
Haha, so simple. I had forgotten about this, thanks for getting back.

This ordering is confusing because of the way message interpolation happens, e.g. `log.info('foo %s', fooVal)`; I didn't even consider putting the message "last". It makes sense under consideration, though it still seems a bit awkward.
