### ISSUE TITLE
Local time option inaccuracies

### ISSUE THREAD

**Issue by leedm777** [trentm/node-bunyan#245]
When using `-L` or `--time local`, the displayed timestamps are inaccurate.

First, their timezone indicator is inaccurate. They are displayed with the trailing `Z`, which indicates UTC. The current timezone should be indicated by `±hhmm`.

Secondly, it presumes that `timezoneOffsetMs` is constant. If a Daylight Saving Time change happens during the logs it is displaying, then it would continue to use the pre-time change offset.

What do you think about using a time formatting library, like [moment](http://momentjs.com/)? I'd be willing to provide a patch if you think that would be an acceptable solution.

**Comment by b-long** [comment]
:+1: I'd like to see this resolved.  @trentm , any thoughts on a patch that includes an extra dependency?

**Comment by cristobal** [comment]
:+1: same here just wondering on how this `time` option format was supposed to work.

**Comment by trentm** [comment]
@leedm777 and others, I'm really sorry for the non-response. I'm not keeping up on bunyan traffic very well.

Yes, I'd be willing to take a patch using momentjs that fixes this. My quick hack was definitely naive.

**Comment by trentm** [comment]
published in bunyan@1.6.0

**Comment by RekhaDasari** [comment]
I am using Bunyan 1.8.0
In that I want to change time zone from UTC to local time.can any please help me out.how can I make a change from UTC to local
