### ISSUE TITLE
bunyan cannot be killed with CTRL-C

### ISSUE THREAD

**Issue by davepacheco** [trentm/node-bunyan#246]
bunyan is not killable with CTRL-C.  Here's a trival case:

```
$ bunyan
^C^C^C^C^C^C^C^C
```

I can also reproduce it with: `bunyan < some_big_logfile.log`.  It's easy to accidentally run this on a very large file and then not be able to kill the process easily.  The workaround is to use CTRL-Z to background it and then kill it (but if you don't know that, you could be waiting a very long time).

This looks like fallout from #126 / #161.  I don't think it's appropriate for bunyan to ignore SIGINT.  For reference, both grep(1) and awk(1), which are similar stream processors that may act directly on files or as part of pipelines, do _not_ install any handlers for SIGINT.  Instead, programs that may be used in pipelines are expected to ignore SIGPIPE.  (They generally don't have to do anything special because the default action for SIGPIPE is to exit the process.  Node is unusual for emitting an Error by default on SIGPIPE, and Node programs intended for use in pipelines should generally explicitly ignore that signal.)

For reference, here's my setup:

```
$ uname -v
Darwin Kernel Version 12.6.0: Wed Mar 18 16:23:48 PDT 2015; root:xnu-2050.48.19~1/RELEASE_X86_64

$ bunyan --version
bunyan 1.3.5

$ node -v
v0.10.28
```

**Comment by trentm** [comment]
Yah, this sucks. Will try to take a look soon.

**Comment by tonylukasavage** [comment]
+1

**Comment by lalitkapoor** [comment]
+1

**Comment by nandanrao** [comment]
+1

**Comment by zbjornson** [comment]
It seems like it would be appropriate to revert #161. The emitter (left-hand side of the pipe) should ignore EPIPE (which is what I think @davepacheco meant) -- see one of the node dev's comments on the issue here: https://github.com/nodejs/node-v0.x-archive/issues/3211#issuecomment-5485933.

**Comment by trentm** [comment]
So, my answer to the original #126 and #161 should have been (as dave and zbjornson have pointed out) to change the input program to something like:

```javascript
var bunyan = require('bunyan');
var log = bunyan.createLogger({name: 'sig'});

var timeout = setTimeout(function () {}, 10000);

process.on('SIGINT', function () {
    log.info('SIGINT here!');
    clearTimeout(timeout);
});

process.stdout.on('error', function (err) {
    if (err.code === 'EPIPE') {
        // ignore
    } else {
        throw err;
    }
});
```

Sorry for the stupid delay.

**Comment by trentm** [comment]
published in bunyan@1.8.9

**Comment by brandonmp** [comment]
this change broke graceful shutdown (or at least the technique I use)

I use something like this:

```
process.on('SIGINT', () => {
  log.info({ event: 'STARTING SHUTDOWN', workers: THROTTLE_LIMIT });
  WORKERS_SHOULD_STOP = true;
});

// when each worker WORKERS_SHOULD_STOP, they call killWorker()

const killWorker = () => {
  deadWorkers += 1
  if (deadWorkers === totalWorkers) {
    process.exit(0)
  }
}
```

This works fine in `bunyan@1.8.5`, but `1.8.9` throws the EPIPE error referenced in OP as soon as I press `ctrl+c`, which kills the shutdown.

I tried including the snippet mentioned above:

```
process.stdout.on('error', function (err) {
    if (err.code === 'EPIPE') {
        // ignore
    } else {
        throw err;
    }
});
```

But this just causes the process to hang silently (ie, the port is still occupied, but there's no action in `stdout`)

reverted back to `1.8.5` for now, but any workarounds here?

**Comment by jclulow** [comment]
@brandonmp I would ignore `EPIPE` errors from the `process.stdout` stream in your program.

**Comment by zbjornson** [comment]
@brandonmp I'm missing the relationship between `WORKERS_SHOULD_STOP` and `killWorker` in your example. I've been trying to make a quick example of graceful cluster shutdown (which is what I assume you're doing), but keep hitting other issues. This roughly works, if it helps:

<details>

```js
const cluster = require("cluster");
const bunyan = require("bunyan");
const log = bunyan.createLogger({name: "myapp"});

if (cluster.isMaster) {
    cluster.fork();
    cluster.fork();

    process.on('SIGINT', () => {
        log.info({event: 'STARTING SHUTDOWN from SIGINT'});
        for (let id in cluster.workers) {
            let worker = cluster.workers[id];
            // Ask workers to shutdown
            worker.send({command: "shutdown"});
            // ...and/or cause worker to close servers and disconnect:
            // worker.disconnect();
            // Allow up to 5 sec for graceful shutdown
            worker.__timeout = setTimeout(() => {
                log.warn("Graceful shutdown timed out, forced exit.");
                worker.kill();
            }, 5000);
            worker.on("disconnect", () => {
                log.info("Worker " + id + " disconnected");
                clearTimeout(worker.__timeout);
            });
        }
    });

} else { // is worker

    // Dummy to keep worker alive:
    var timeout = setTimeout(function () {}, 100000);

    process.on("SIGINT", () => {
        // Ignore SIGINT that propagates to workers
    });

    process.on("message", (msg) => {
        if (msg.command === "shutdown") {
            log.info("Got shutdown");
            setTimeout(function () {
                log.info("Worker shut down gracefully");
                clearTimeout(timeout);
                process.exit();
            }, 1000 * Math.random());
        }
    })
}

process.stdout.on('error', function (err) {
    if (err.code === 'EPIPE') {
        // ignore
    } else {
        throw err; // See note below
    }
});

```
</details>

(However, I'm hitting issue #108 or something similar to it. I only use graceful shutdown in production so devs don't waste time waiting for graceful shutdown, and in turn I only use Bunyan CLI in dev.)

---

Does your application work without piping it to the Bunyan CLI utility?

**Comment by trentm** [comment]
@brandonmp As @zbjornson indicated: Some more details on what you are seeing would be helpful to try to repro what you are seeing. Are your workings using the bunyan *CLI* (which is what this ticket changed)?  Also, if you could open a separate issue for what you are hitting, that would help ensure it doesn't get lost.

**Comment by brandonmp** [comment]
Thanks guys, posted in its own issue w/ sample repo. see #491
