### ISSUE TITLE
How to intercept all the logs of bunyan?

### ISSUE THREAD

**Issue by nitulkukadia** [trentm/node-bunyan#247]
Ex:
var bunyan = require('bunyan');
var log = bunyan.createLogger({name: 'myapp'});
log.info('hi');
Output:

$ node hi.js
   {"name":"myapp","hostname":"banana.local","pid":40161,"level":30,"msg":"hi","time":"2013-01-04T18:46:23.851Z","v":0}

I want to extra logic for each log, such as: prefix, suffix, parse this json to object, etc...

**Comment by trentm** [comment]
My apologies for the crazy long delay. I fell of maintaining Bunyan for a while.

See https://github.com/trentm/node-bunyan#stream-type-raw
Here is an example: https://github.com/trentm/node-bunyan/blob/master/examples/raw-stream.js

Please re-open if it isn't clear enough in the docs what to do.
