### ISSUE TITLE
Is it possible to change the way bunyan traces its log file ?

### ISSUE THREAD

**Issue by Limezest** [trentm/node-bunyan#265]
Hi,

I use bunyan to write my NodeJS app logs, then I run a script on a regular basis. It uploads this .log file and moves it in an other directory. I thought when the file disappeared from the directory, Bunyan would create another one, but it actually follows the first file into the other directory (because of the inode?).

This is an expected behavior I suppose but are there any parameters that could disable this ?

**Comment by RBLU** [comment]
This is the normal behavior of unix/linux/osx based operating systems and has nothing to do with bunyan itself: If process 1 opens a file and process 2 moves/copies the file, process 1 keeps on writing to the initial file. 

Your options are: 
- https://github.com/trentm/node-bunyan#stream-type-rotating-file
- use a tool like linux logrotate with the copytruncate option:  http://linuxcommand.org/man_pages/logrotate8.html
- Do it yourself:

put something like this in your app. 

```javascript
    var log = bunyan.createLogger(...);
     ...
     process.on('SIGUSR2', function () {
         log.reopenFileStreams();
     });
```
and after you moved the file send SIGUSR2 to your app process so bunyan can reopen its filestreams.

**Comment by trentm** [comment]
What @RBLU said (thanks for answering so well!)

**Comment by Limezest** [comment]
Thanks for the fast and detailed answers.
Regards
