### ISSUE TITLE
Initiate a logger with no default stream

### ISSUE THREAD

**Issue by bioball** [trentm/node-bunyan#267]
I'd like to be able to initiate a Logger instance that doesn't log to any stream by default, so I can programmatically call `addStream` as needed. From reading the source code, this isn't possible. Is this planned at all? I'd be happy to submit a PR for it.

**Comment by trentm** [comment]
Should be able to use `streams: []`. E.g.:

```
$ cat nostreams.js
var bunyan = require('bunyan');
var log = bunyan.createLogger({
    name: 'nostreams',
    streams: [],
    level: 'info'
});

log.info('one');

log.addStream({
    stream: process.stdout
});
log.info('two');

$ node nostreams.js
{"name":"nostreams","hostname":"grape.local","pid":6063,"level":30,"msg":"two","time":"2015-06-16T06:07:20.524Z","v":0}
```

Cheers.
