### ISSUE TITLE
rotating-file can't be found when it's required in multiple modules/files

### ISSUE THREAD

**Issue by cjMdGit** [trentm/node-bunyan#276]
Hi all,

Thanks for your help in advance!

I am using bunyan 1.4.0 and node 0.10.24 on Linux. I have define a log with bunyan in a local file utils.js:

```
exports.getLogger = function (logLevel) {

   var log = bunyan.createLogger({
      name: 'log_test',
      streams: [
        {
          type: 'rotating-file',
          path: __dirname + '/logs/node.log', 
          level: logLevel || 'info',
          period: '6000ms', 
          count: 7      
        },
        {
          path: './logs/node_err.log', 
          level: 'error'
        },
      ],
      serializers: {
         req: reqSerializer,
         res: bunyan.stdSerializers.res
      }
   });

   return log;
};
```

The utils.js has to be required in several other files. I find that if it is required in 2 files, both of them use log.info() and log.error(), I'll get ENOENT, rename '/.../node.log.X',  and X is usually the 2nd last number.  for e.g, if the rotation count is 6, and X is 5 almost all the time.

If I include the utils.js in only one file by require(), the rotation works fine.

**Comment by cjMdGit** [comment]
sorry for typos.  The ENOENT error comes up when the utils.js is required in more than 2 files.

**Comment by Rcomian** [comment]
If you call `getLogger` multiple times you're going to be running multiple instances of the file rotator. Each one will try to rotate the files and they'll conflict with each other.
You need to create a single log instance, cache it and return it. There's currently no way of having multiple file rotators play nice together.

I'd change your code to something like:

```javascript
var log = null
exports.getLogger = function (logLevel) {
  log = log || bunyan.createLogger({
    name: 'log_test',
    streams: [
    {
      type: 'rotating-file',
      path: __dirname + '/logs/node.log', 
      level: logLevel || 'info',
      period: '6000ms', 
      count: 7
    },
    {
      path: './logs/node_err.log', 
      level: 'error'
    },
    ],
    serializers: {
      req: reqSerializer,
      res: bunyan.stdSerializers.res
    }
  });

  return log;
};
```

**Comment by Rcomian** [comment]
This appears to be a very common mistake. We can't do much at the moment when working between processes, but when creating multiple rotators in the same process, we can detect that.

My 3rd party rotating file stream will detect that you're trying to do this and fail with an error immediately so you know what's wrong.

[https://www.npmjs.com/package/bunyan-rotating-file-stream](https://www.npmjs.com/package/bunyan-rotating-file-stream)

**Comment by trentm** [comment]
I think @Rcomian answered this. Thanks.

**Comment by ismailkattakath** [comment]
@Rcomian , Thank you. The issue has been fixed.
