### ISSUE TITLE
Bunyan and Node-Webkit

### ISSUE THREAD

**Issue by amoussard** [trentm/node-bunyan#301]
Hello @trentm,

I currrenty develop a node webkit application, and a condition in your code cause a big fail.

```javascript
if (typeof (window) === 'undefined') {
    var os = require('os');
    var fs = require('fs');
    try {
        /* Use `+ ''` to hide this import from browserify. */
        var dtrace = require('dtrace-provider' + '');
    } catch (e) {
        dtrace = null;
    }
} else {
    var os = {
        hostname: function () {
            return window.location.host;
        }
    };
    var fs = {};
    var dtrace = null;
}
```

Node-Webkit is based on node, and have a window object, so it must not be considered as a "browser". This type of app can use the filesystem and the logic is "server-side".

There is a proper way to bypass this?

Thank you.

**Comment by fleg** [comment]
interesting coincidence, I also developing nw.js app and I was surprised when find out that bunyan didn't work under nw.js with file streams

**Comment by adam-lynch** [comment]
:+1:

**Comment by luzlab** [comment]
Would be great to see one of the pull requests fixing this issue to get merged!

**Comment by kohenkatz** [comment]
:+1:

**Comment by trentm** [comment]
see #311
