### ISSUE TITLE
parentLogger.child(options) does not inherit 'hostname' field of parent

### ISSUE THREAD

**Issue by RBLU** [trentm/node-bunyan#303]
The child() call is setting the 'hostname' field in client with os.hostname() instead of inheriting from parent. So when the parent uses a non-default 'hostname' the child does not inherit this field.
 
For us this caused quite a bit of confusion when log messages would be "missing" on our central logserver (because of the usual filter by hostname they never showed up, they had the physical hostname in there, where we expected the hostname that was specifically set in all parent loggers).  

Same applies to PID, but there it did not hurt us.

is this intentional or a bug?

**Comment by kfiroo** [comment]
I'm having the same issue. I believe it's a bug.
My current solution is to wrap the 'create child' method and ensure the hostname param is passed to the child logger.
I guess you can do the same with the PID.
