### ISSUE TITLE
question - why does this code print to info.log

### ISSUE THREAD

**Issue by ORESoftware** [trentm/node-bunyan#305]
the following isolated Bunyan code prints to my error.log and my info.log, but I just want it to print to my error.log:

```javascript

var bunyan = require('bunyan');


var logger = bunyan.createLogger({
    name: 'SmartConnect',
    src: true,
    streams: [
        {
            level: 'info',
            stream: process.stdout
        },
        {
            level: 'info',
            path: './info.log'
        },
        {
            level: 'error',
            path: './error.log'
        },
        {
            level: 'error',
            stream:process.stderr
        }
    ]
});

logger.error('purple');   // shouldn't this statement write just to error.log?

```

I am confused, please help, thanks

**Comment by ORESoftware** [comment]
Ok this seems to be because error is a "lower" level than info, so anything logged to error also gets logged to info, I don't like this, but I guess I will live with it...there should be logging levels that are on the same level of the hierarchy

**Comment by trentm** [comment]
See https://github.com/trentm/node-bunyan/issues/334 and https://github.com/trentm/node-bunyan/issues/320

**Comment by ORESoftware** [comment]
thanks, mostly this is due to my naivete of standard logging systems

**Comment by CTJyeh** [comment]
So what is the best way to restrict output to only specified files? or is that not good practice?

**Comment by trentm** [comment]
Sounds like this is a duplicate question to #340.

@CTJyeh, @ORESoftware Here is an example that demonstrates a couple examples of how to use a custom Bunyan stream to do something like this: <https://github.com/trentm/node-bunyan/blob/master/examples/specific-level-streams.js>
