### ISSUE TITLE
Want to disable logging via environment variable

### ISSUE THREAD

**Issue by psnider** [trentm/node-bunyan#308]
I use mocha+chai for my tests, and depend upon easy to read test reports produced by continuous testing. However, when I use logging, the logged data is intermixed with the test report.

I'm doing all of this with my development configuration, and so I don't want a special configuration just to run tests. I think the easiest way to do this is to define an environment variable in my build file that runs my tests:
```
BUNYAN_OFF=true mocha  -R spec commonjs/service.tests.js
```

Is there an existing mechanism to do this?
For now, I'm using a simple modification to mkLogEmitter:
```
function mkLogEmitter(minLevel) {
    return function () {
        if (process.env.BUNYAN_OFF) {
            return
        }
        // remainder of function as before
```
If this is the best way, let me know if you want a pull request.

**Comment by tiborb** [comment]
Same issue here

**Comment by sonnyp** [comment]
duplicate https://github.com/trentm/node-bunyan/pull/148
