### ISSUE TITLE
Not able to see req.body getting logged in trace

### ISSUE THREAD

**Issue by royfk21** [trentm/node-bunyan#309]
Hello,

We are using Express 4.0 (^4.9.5) and bunyan (^1.2.1) for logging on a nodejs web project.
Express already has bodyParse in use. app.use(bodyParser.json());
However, inspite to log level set to trace/info, we are unable to see req.body getting logged.
Only req.headers are visible. Is there another setting that controls this?
Doesn't the default " (bunyan.stdSerializers).req" log the req.body upfront?

var log = bunyan.createLogger({
      name: loggingConfiguration.loggerName,
      streams: [{
          type: 'rotating-file',
          path: 'app.log,
          level: 'trace',
          period: '1d', 
          count: '30'
        }
        {
          level: 'trace',                 
          stream: process.stdout          
        }],
      serializers: {
        err: (bunyan.stdSerializers).err,
        req: (bunyan.stdSerializers).req,
        res: (bunyan.stdSerializers).res
        }
    });
	
log.trace({req : req}, "Record Request");

During debug session, we are able to see req.body and at the time of logging we are logging the entire req object as it is. Would be grateful for inputs here.

Thanks,
Roy

**Comment by royfk21** [comment]
Never mind i figured it out. Thanks.

**Comment by Pixboh** [comment]
How did you do to solve this?
