### ISSUE TITLE
Log process.stdout and file

### ISSUE THREAD

**Issue by marales** [trentm/node-bunyan#314]
I would like to log the messages in both stdout and file on every logging level, i didn't find an configuration. It's this possible ?

**Comment by trentm** [comment]
@marales Apologies for the delay in responding (see https://github.com/trentm/node-bunyan/issues/335 if you are curious about that).

I think this should do what you want:

```
var bunyan = require('bunyan');
var log = bunyan.createLogger({
    name: 'issue314',
    streams: [
        {
            stream: process.stdout,
            level: 'trace'
        },
        {
            path: '/var/log/a.log',
            level: 'trace'
        }
    ]
});
```
