### ISSUE TITLE
Move 'mv' from optionalDependencies to devDependencies

### ISSUE THREAD

**Issue by pktippa** [trentm/node-bunyan#324]
RotatingFileStream is the feature expected for using logger node module, but the feature is not working when we install bunyan with --no-optional.

Can you please move the 'mv' module from optionalDependencies to devDependencies

**Comment by pktippa** [comment]
@trentm Can you please comment on this issue?

**Comment by trentm** [comment]
Why are you using "--no-optional"? The `mv` dep is required for using the (optional) `RotatingFileStream`. It isn't a dependency for *developing* Bunyan (e.g. for running its test suite), hence isn't a `devDependency`.

**Comment by nmschulte-aviture** [comment]
What's the rationale for `mv` being optional?  That seems to be the root of these issues. https://github.com/trentm/node-bunyan/issues/529#issuecomment-447146136

**Comment by adamelliotfields** [comment]
Agree that it's clearly not a devDependency. You'd have the same issue if you ran `npm install` with `NODE_ENV=production`.

A good use for an optional dependency is if it's something really heavy that you don't need - for example - `sqlite`, which requires Python and Make to build on Alpine.

`mv` only has 3 dependencies - `ncp`, `mkdirp`, and `rimraf` which are all pretty light and also most likely used by other dependencies already. I think it's a good candidate to move to production dependencies.
