### ISSUE TITLE
Can not set log level '0'

### ISSUE THREAD

**Issue by sometimesalready** [trentm/node-bunyan#325]
I want to log all levels so I create logger like this:
```javascript
let logger = bunyan.createLogger({
  name: 'name',
  level: 0
});

logger.level(); // 30
```
but as you see. the level is set to default without any warnings.
It is not a bug, but it is not predictable behavior for my opinion.

**Comment by trentm** [comment]
I think I'll call this one a bug. If a string or number is given for level, it should either work as expected or throw an error to explicitly point out why it is invalid.

Separately, bunyan could reasonably get a feature request to have ALL (0) and OFF/NONE (Infinity?) values to be able to have terms for turning logging fully on or off.

**Comment by sometimesalready** [comment]
PR #336 allow to set log level to '0'
