### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by omrilitov** [trentm/node-bunyan#327]
Bunyan is a great project and it's widely used, but there seems to be plenty of issues and PRs, and most of them don't get answered.
Also the Last commit was more then 3 months ago
Is the project still in development? Is it still alive?
@trentm would love for you to comment

**Comment by mickaeltr** [comment]
+1

**Comment by trentm** [comment]
Thanks for asking. I'm writing up a CONTRIBUTING.md, a plan to do a triage of all issues/PRs, leading into asking others for help with Bunyan maint. Hopefully I'll have the former this week -- though I know it is pushing it to ask for more patience.

Current CONTRIBUTING.md: https://gist.github.com/trentm/fe0b37cc71fbee52eaba
The "Mea culpa" and "A plan" sections will likely move out of there to a blog post or something.

**Comment by trentm** [comment]
See https://github.com/trentm/node-bunyan/issues/335

**Comment by omrilitov** [comment]
Awesome, glad to hear!
