### ISSUE TITLE
Log Rotation Fails on Short Lived Processes

### ISSUE THREAD

**Issue by domrein** [trentm/node-bunyan#329]
Logs don't rotate on processes that aren't alive when the specified period elapses. For example, a log that should rotate every day will not rotate if the process just lives for a couple of minutes every day and does not run over midnight. I'll have a pull request for this shortly.

**Comment by domrein** [comment]
https://github.com/trentm/node-bunyan/pull/330

**Comment by Rcomian** [comment]
If you need a fix for this right now, my rotating file stream component should handle this case:

[https://www.npmjs.com/package/bunyan-rotating-file-stream](https://www.npmjs.com/package/bunyan-rotating-file-stream)

**Comment by trentm** [comment]
@domrein Thanks for this. Merged. This'll be in version 1.8.0.

Also, FYI that I'm going to start pointing people to @Rcomian's module for file rotation.
