### ISSUE TITLE
Higher levels logging into lower level streams.

### ISSUE THREAD

**Issue by AnuroopKuppam** [trentm/node-bunyan#334]
I am trying to use bunyan in my nodejs application, however I stuck with this bizarre behaviour.
Defining the logger like so:
```javascript
var info = bunyan.createLogger({
    name: 'Test',
    streams: [
        {
            path: './logger/fatal.log',
            level: 'fatal'
        },
        {
            path: './logger/error.log',
            level: 'error'
        },
        {
            path: './logger/warn.log',
            level: 'warn'
        },
        {
            path: './logger/info.log',
            level: 'info'
        },
        {
            path: './logger/debug.log',
            level: 'debug'
        },
        {
            path: './logger/trace.log',
            level: 'trace'
        }
    ]
});
```
And I am calling them in a function like so:

```javascript
var func = function () {
    info.fatal("FATAL!");
    info.error("ERROR!");
    info.warn("WARN!");
    info.debug("DEBUG!");
    info.info("INFO");
    info.trace("TRACE");
}
```
Now the predictable behaviour would be 
**fatal.log** has ``{"name":"Test","hostname":"ENIGMA","pid":16793,"level":60,"msg":"FATAL!","time":"2016-01-21T09:12:34.293Z","v":0}``
**error.log** has ``{"name":"Test","hostname":"ENIGMA","pid":16793,"level":50,"msg":"ERROR!","time":"2016-01-21T09:12:34.295Z","v":0}``
and so forth.

However, on my application,
**fatal.log** has ``{"name":"Test","hostname":"ENIGMA","pid":16793,"level":60,"msg":"FATAL!","time":"2016-01-21T09:12:34.293Z","v":0}``
**error.log** has 
``{"name":"Test","hostname":"ENIGMA","pid":16793,"level":60,"msg":"FATAL!","time":"2016-01-21T09:12:34.293Z","v":0}
{"name":"Test","hostname":"ENIGMA","pid":16793,"level":50,"msg":"ERROR!","time":"2016-01-21T09:12:34.295Z","v":0}``
**warn.log** has
``{"name":"Test","hostname":"ENIGMA","pid":16793,"level":60,"msg":"FATAL!","time":"2016-01-21T09:12:34.293Z","v":0}
{"name":"Test","hostname":"ENIGMA","pid":16793,"level":50,"msg":"ERROR!","time":"2016-01-21T09:12:34.295Z","v":0}
{"name":"Test","hostname":"ENIGMA","pid":16793,"level":40,"msg":"WARN!","time":"2016-01-21T09:12:34.296Z","v":0}``
and so forth.

The higher level logs are getting into the lower streams.
Is this common behaviour?

**Comment by trentm** [comment]
@AnuroopKuppam Yes, that is the intention. Saying `"level": "warn"` is intended to mean "all log records at level warn *and above*".

**Comment by tobiasfielitz** [comment]
Are there any filters or a workaround for this? I get the idea of log levels, but it still doesn't make sense to me to log the same line multiple times.

**Comment by Jokero** [comment]
I also find this behavior very strange. So confusing. It looks like `bunyan` does not solve the main problem of logging :smile:
