### ISSUE TITLE
Log rotation fails for period > max timeout, and often also for smaller periods

### ISSUE THREAD

**Issue by Oblosys** [trentm/node-bunyan#344]
The problem is that whenever the rotation timeout fires before reaching the target rotation time, it will be advanced to the next rotation time, rather than finish the current one. In case the period is larger than the maximum timeout, it is guaranteed to fire before the target time, and will therefore be extended indefinitely without ever rotating. However, even for smaller periods, the timeout may fire just before the target time, causing it to skip a rotation. On my machine this happened consistently for timeouts over a minute.

**Comment by Oblosys** [comment]
Extended duplicate of issue #333

**Comment by Rcomian** [comment]
If you need a fix for this right now, my rotating file stream component should handle this case:

[https://www.npmjs.com/package/bunyan-rotating-file-stream](https://www.npmjs.com/package/bunyan-rotating-file-stream)
