### ISSUE TITLE
Bunyan 1.7.1 crashed: TypeError: Cannot read property 'pipe' of null

### ISSUE THREAD

**Issue by ajitprak** [trentm/node-bunyan#371]
I am trying change log levels dynamically using bunyan dtrace, It was working fine for older versions of node, After taking the latest node update 4.4.0, I am getting the above error when I run the command sudo bunyan -p *. Please help me.

**Comment by oliverdunk** [comment]
Can confirm, could someone take a look at this perhaps?

**Comment by trentm** [comment]
duplicate of #370
