### ISSUE TITLE
no logging if your error object has level property

### ISSUE THREAD

**Issue by weagle08** [trentm/node-bunyan#391]
If you create an error object with a level property {message: 'my message', level: 'error'} then bunyan does not log output.

**Comment by cressie176** [comment]
Also seeing this.

```
const bunyan = require('bunyan');
const log = bunyan.createLogger({ name: 'foo' });
log.info({ level: 'info' }, 'Hello World')
```
Fails to log

**Comment by michaelnisi** [comment]
Looks like a bug to me, the docs state:

    - level: Required. Integer. Added by Bunyan. Cannot be overridden. See the "Levels" section.

But log records having a `level` apparently seem to interfere:

```js
var bunyan = require('bunyan');
var log = bunyan.createLogger({ name: 'foo' });
var levels = [
  undefined, // no
  null, // no
  0, // no
  10, // no
  20, // no
  30, // yes "level":30,"msg":"30"
  40, // yes "level":40,"msg":"40"
  'hello', // no
  'trace', // no
  'info' // no
]
levels.forEach(function (l) {
  log.info({ level: l }, l)
})
```

**Comment by efdee** [comment]
This bug still exists. Took me quite a bit of debugging before I realised what's wrong.
At the very least display a warning or throw an error if a 'level' property is passed.
