### ISSUE TITLE
Error when bundling with Webpack

### ISSUE THREAD

**Issue by raybooysen** [trentm/node-bunyan#392]
Hi all

Using webpack bundling Bunyan and I'm seeing the following when the bundling is complete:

```
WARNING in ./~/bunyan/~/dtrace-provider/dtrace-provider.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./build in /home/ray/source/ca.ui.shell.core/node_modules/bunyan/node_modules/dtrace-provider
 @ ./~/bunyan/~/dtrace-provider/dtrace-provider.js 17:22-81
```

Any ideas?

Using version 1.8.0 of bunyan

**Comment by DanForbes** [comment]
Was having the same issue and came across [this note on the README.md](https://github.com/trentm/node-bunyan#webpack).

**Comment by iDVB** [comment]
Still having the same issue, even after setting up the `noParse`

**Comment by cdagli** [comment]
Having below fixed the issue for me: 

`noParse: [/dtrace.js$/, /serializer.js$/],`

Seems like noParse sends the filename as content, found this out while trying as it a function: 
`// since webpack 3.0.0
noParse: function(content) {
  return /jquery|lodash/.test(content);
}`
