### ISSUE TITLE
systemjs support

### ISSUE THREAD

**Issue by rweng** [trentm/node-bunyan#402]
Hi there,

does node-bunyan work w/ systemjs? I tried to get it to work, but got into dependency hell where bunyan required 'os', 'fs', 'stream', ... It says in the readme that bunyan should work in the browser when used w/ browserify, so enabling it for systemjs should be possible, shouldn't it?

Thanks so much for bunyan, really like it on the server-side :)

Robin

**Comment by andreas-wagner** [comment]
I also have this problem but with this line in bunyan.js
`var mv = require('mv' + '');`

This prevents jspm/SystemJS from detecting a require call properly, thus I will always get the error
"rotating-file" stream type is not supported: missing "mv" module.

Any way around this?

**Comment by trentm** [comment]
I don't know anything about systemjs to know if there would be hurdle in adapting node-bunyan to be able to use it. Happy to look at PRs that would add this. A start would be looking at the current env detection code in bunyan here: https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L29-L63

**Comment by andreas-wagner** [comment]
Apparently things like

var mv = require('mv' + '');

are not resolved, thus mv is always bad and I can't use rotating-file.

Why are you doing this require hack? What for?

**Comment by trentm** [comment]
That hack is for browserify.

**Comment by andreas-wagner** [comment]
Opened a ticket with SystemJS and it is solved now. See [here](https://github.com/systemjs/systemjs/issues/1453)

**Comment by trentm** [comment]
Thanks for getting back!
