### ISSUE TITLE
Stops logging to file, but continues with other stream?

### ISSUE THREAD

**Issue by logidelic** [trentm/node-bunyan#415]
Hello,

My node app sets up bunyan to log to two different streams:

```
var log = bunyan.createLogger({name:'doodle', streams:[
    {level:'info',type:'raw',stream:logStream},
    {level:'debug',path:__dirname+'/some-logfile.json'}
]});
```

The first (`logStream`) is a `new Stream()` that I use to to format and output to the stdout. This works just fine. The second outputs to a file.

What happened recently is that bunyan silently stopped outputting to the file in the middle of the app execution, though it continued outputting to the raw stream.

Does anyone have suggestions on what could possibly cause this, or any way to debug it?

If it matters, my node app was started using nohup, so the stdout stuff was going to a file nohup.out. This file was continuing to be appended to, while the JSON log file was no longer being used. Restarting the app got things going again, of course.

**Comment by rigor789** [comment]
I too have ran into this issue, wondering if you found anything useful to debug this?

In my case, I have two streams, one is to stdout, and one goes through a custom stream that emits via websockets. After a little while the custom stream stops receiving logs, while the stdout keeps working.

**Comment by logidelic** [comment]
Glad you figured it out. In my case I'm not 100% sure if this is still happening. Made many changes since then and possibly fixed an unrelated issue that was somehow causing this. I'll close this for now until I see the problem again.
