### ISSUE TITLE
DtraceProviderBindings errors on OS X (maybe related to "mv")

### ISSUE THREAD

**Issue by franky-continu** [trentm/node-bunyan#424]
So following #216 instructions which are poorly tested, I went ahead and install bunyan with

` $ npm install --no-optional`

But when I do that I get an error indicating that rotating-file is not available because `mv` module is not present.

```
12:49 $ npm start

> continu-api@1.0.0 start /Users/franky/Workspace/continu/continu-api
> node server.js


assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: "rotating-file" stream type is not supported: missing "mv" module
    at Logger.addStream (/Users/franky/Workspace/continu/continu-api/node_modules/bunyan/lib/bunyan.js:606:16)
    at /Users/franky/Workspace/continu/continu-api/node_modules/bunyan/lib/bunyan.js:469:18
    at Array.forEach (native)
    at new Logger (/Users/franky/Workspace/continu/continu-api/node_modules/bunyan/lib/bunyan.js:468:25)
    at Object.<anonymous> (/Users/franky/Workspace/continu/continu-api/server.js:29:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

```

Then I install `mv`

```
$ npm install mv

> dtrace-provider@0.6.0 install /Users/franky/Workspace/continu/continu-api/node_modules/dtrace-provider
> node scripts/install.js


> dtrace-provider@0.3.2 install /Users/franky/Workspace/continu/continu-api/node_modules/heywatch/node_modules/dtrace-provider
> node scripts/install.js

---------------
Building dtrace-provider failed with exit code 1 and signal 0
re-run install with environment variable V set to see the build output
---------------
continu-api@1.0.0 /Users/franky/Workspace/continu/continu-api
├─┬ bunyan@1.8.1
│ ├── dtrace-provider@0.6.0 
│ └── safe-json-stringify@1.0.3 
```

And I can already see the DTrace Provider which I'm certain will throw the error. 

```
Moment Timezone 0.3.1 was already loaded with data from 2015a
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
```
We need to get to the bottom of this issue.

**Comment by trentm** [comment]
@franky-continu A few notes:

1. `npm install mv` attempted to build and/or install dtrace-provider !?  Can you reproduce that if you start with a clean `node_modules` subdir?

2. Your npm install shows bunyan@1.8.1 with a dtrace-provider@0.6.0 dep (working) and ... *something* else in your app that has a dep on dtrace-provider@*0.3.2*.  I believe it is that other older dtrace-provider dep that is causing the build problem here. Perhaps we can find what has that dep with the output of `npm ls` in that directory.

3. If you can repro these errors, what version of node are you using?

Here is a run through of me successfully using bunyan (with `--no-optional`) and separately installing `mv` to use `rotating-file`:

```
$ uname -v
Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64

$ node --version
v4.5.0


$ ls node_modules
ls: node_modules: No such file or directory

$ npm install bunyan --no-optional
bunyan@1.8.1 node_modules/bunyan

$ cat hi.js
var bunyan = require('bunyan');
var log = bunyan.createLogger({name: 'hi'});
log.info('hi there');

$ node hi.js
{"name":"hi","hostname":"danger0.local","pid":41985,"level":30,"msg":"hi there","time":"2016-08-26T07:14:00.426Z","v":0}


$ cat rota.js
var bunyan = require('bunyan');
var log = bunyan.createLogger({
    name: 'rota',
    streams: [{
        type: 'rotating-file',
        path: '/var/tmp/rota.log',
        period: '1d',
        count: 3
    }]
});
setInterval(function () {
    log.info('hi there');
}, 1500);

$ node rota.js
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: "rotating-file" stream type is not supported: missing "mv" module
    at Logger.addStream (/Users/trentm/tm/play/node_modules/bunyan/lib/bunyan.js:606:16)
var bunyan = require('bunyan');
    at /Users/trentm/tm/play/node_modules/bunyan/lib/bunyan.js:469:18
...

$ npm install mv
mv@2.1.1 node_modules/mv
├── ncp@2.0.0
├── mkdirp@0.5.1 (minimist@0.0.8)
└── rimraf@2.4.5 (glob@6.0.4)

$ node rota.js
^C

$ cat /var/tmp/rota.log
{"name":"rota","hostname":"danger0.local","pid":42116,"level":30,"msg":"hi there","time":"2016-08-26T07:16:23.577Z","v":0}
{"name":"rota","hostname":"danger0.local","pid":42162,"level":30,"msg":"hi there","time":"2016-08-26T07:16:58.788Z","v":0}
```

Please re-open this ticket if you can repro, and with some details like your platform, node version, and context on the other deps in your app. Cheers.

**Comment by franky-continu** [comment]
@trentm OMG man thanks so much for the time and the detailed reply. I'll do more testing here ASAP (in around 2 or 3 hours). To respond something here and looking at #216 I was using at the time 

> npm ERR! Darwin 15.4.0
> npm ERR! argv "/Users/franky/.nvm/versions/node/v6.1.0/bin/node" "/Users/franky/.nvm/versions/node/v6.1.0/bin/npm" "start"
> npm ERR! node v6.1.0
> npm ERR! npm  v3.8.6
> npm ERR! code ELIFECYCLE
> npm ERR! continu-api@1.0.0 start: `node server.js`
> npm ERR! Exit status 1


I'll do more testing and will try to post more info. I don't think the issue has been fixed because I keep seeing people posting it, it comes from using node libraries like maybe mv in mac as it is, meaning you get your mac you get node you get some libraries like bunyan, and then you see the warnings.

I keep seeing people posting about it, and will check. I have a typical restify mongoose bunyan library, (moment, etc) nothing too fancy or weird. And `DtraceProviderBindings` always have shown or at least since the node 4.0 project merged, this is my recollection but could be mistaken as to when it started.

We are now though using node 5.0 because we couldn't move up stream due to that and other issues, we are a small team so we didn't had the time to look into it that much.

Thanks again, I'll post something with more details soon.
