### ISSUE TITLE
A new Bunyan stream for Amazon's Dynamo DB

### ISSUE THREAD

**Issue by ssmereka** [trentm/node-bunyan#425]
I created a stream for Bunyan to store logs in amazon's document storage service Dynamo DB.  Wondering if you wanted to add it to the list of [3rd party streams in your Readme](https://github.com/trentm/node-bunyan#third-party-streams).

Thanks!

**Comment by trentm** [comment]
@ssmereka Definitely. Where is your module? Or you could give me a PR adding to the README.md.

I also wouldn't cry if someone started a "3rd-party packages" or "Related packages" or "Awesome Bunyan" (in the style of https://github.com/vinta/awesome-python and https://github.com/ziadoz/awesome-php) page on the [wiki](https://github.com/trentm/node-bunyan/wiki). :)

**Comment by ssmereka** [comment]
Would probably help to include a link to the repo lol,  [bunyan-dynamo](https://github.com/ssmereka/bunyan-dynamo).  See pull request #430.

Sorry, but I would require tears to create and manage an ```awesome-bunyan``` repo.  :)

**Comment by ssmereka** [comment]
bump! ^ ^  -- The pull request is pretty simple and has been complete for 18 days.

**Comment by ssmereka** [comment]
Please accept my pull request, it's so simple.  bump again ^ ^

**Comment by trentm** [comment]
@ssmereka Sorry for the delay getting back to this. A while back I removed the direct links in the README and moved refs to 3rd-party Bunyan-related stuff to https://github.com/trentm/node-bunyan/wiki/Awesome-Bunyan    I've added the link to bunyan-dynamo there.  Thanks!
