### ISSUE TITLE
Exit codes not passed through

### ISSUE THREAD

**Issue by DonutEspresso** [trentm/node-bunyan#433]
Given the following `err.js` file:

```
if (process.argv[2] === '--abort') {
    console.warn('aborting');
    process.abort();
} else {
    console.warn('exiting 0');
    process.exit();
}
```

Then in the normal case:
```
aliu at lgml-aliu in ~/Downloads/test
$ node err.js
exiting 0
aliu at lgml-aliu in ~/Downloads/test
$ echo $?
0
aliu at lgml-aliu in ~/Downloads/test
$ node err.js | bunyan
exiting 0
aliu at lgml-aliu in ~/Downloads/test
$ echo $?
0
```

In the event of non zero exit code:
```
aliu at lgml-aliu in ~/Downloads/test
$ node err.js --abort
aborting
Abort trap: 6
aliu at lgml-aliu in ~/Downloads/test
$ echo $?
134
aliu at lgml-aliu in ~/Downloads/test
$ node err.js --abort | bunyan
aborting
aliu at lgml-aliu in ~/Downloads/test
$ echo $?
0
```

It'd be nice to get the exit code passed through by default, and if not, a flag would be better than nothing. I poked through the code and didn't see anything that might enable this, but I may have missed it.

**Comment by trentm** [comment]
@DonutEspresso My understanding of shell pipelines is that there is nothing the end of the pipeline can do. I.e. `bunyan` doesn't ever see the exit status of the `node err.js --abort`. 

A couple possilibities:

1. bring the Bunyan pretty formatting into the app itself, as requested in #13 (or something like it).
2. use `set -o pipefail` in your shell (assuming you are using Bash) or for scripts that do this, and Bash will terminate the pipeline with a non-zero exit status if any command in the pipeline exits non-zero

**Comment by DonutEspresso** [comment]
Oops, I totally forgot to close this once I figured out the shell I was on hadn't been configured correctly. It was totally #2 - sorry for the noise!

**Comment by thanpolas** [comment]
Solution 1 which is related to #13 is not ready yet, the feature request is still open and i see no out-of-the-box way to perform in-app pretty formatting.

Solution 2 is a feature that is only available on bash shells. Unfortunately that is not the case for the CI we use circleCI, I get an error there of type:

```
sh: 1: set: Illegal option -o pipefail
```

I used the following on my npm test:

```
set -o pipefail && (./node_modules/.bin/mocha -b test/unit &&./node_modules/.bin/mocha -b test/api ) | ./node_modules/bunyan/bin/bunyan
```

So what's left for me to do here?

**Comment by trentm** [comment]
@thanpolas You could write the log output to a file (either via config of the bunyan logger, or via shell redirection) and pretty-print it later if debugging some automated build issue. I.e. avoid piping directly to bunyan (especially in an automated build command).
