### ISSUE TITLE
Circular serialization

### ISSUE THREAD

**Issue by fbeuvens** [trentm/node-bunyan#434]
With obj being a reference to a same object `{}`, when I create a log of the form
```
{
  key1: obj
  key2: obj
}
```

I end up with a serialized output of the form
```
{ 
  key1: {},
  key2: "[Circular]"
}
```

Is it an intended behavior? To me, the circular reference should only be present in the case an object has a key with a reference to itself, but this is not the case here.

**Comment by voxpelli** [comment]
See #427 for same reported thing

**Comment by trentm** [comment]
@fbeuvens Unfortunately yah. I don't disagree with you, but I'm not sure if there is an efficient implementation of "the case an object has a key with a reference to itself". I'd be happy to be proven wrong there!

Also, if ever you can, posting examples of actual log records in your usage that hit this can help guide changes.

**Comment by trentm** [comment]
@voxpelli thanks a lot for the link to the other ticket, that helps me a lot!

**Comment by ORESoftware** [comment]
This can stringify circular / cyclical objects 

```
export const customStringify = function (v: object) {
  let cache = new Map<any, true>();
  return JSON.stringify(v, function (key, value) {
    if (typeof value === 'object' && value !== null) {
      if (cache.get(value) === true) {
        // Circular reference found, discard key
        return;
      }
      // Store value in our collection
      cache.set(value, true);
    }
    return value;
  });
};
```

**Comment by voxpelli** [comment]
@ORESoftware Rather than commenting on closed issues, either open a new issue or a PR if you have a code contribution
