### ISSUE TITLE
Temporary mute logging

### ISSUE THREAD

**Issue by olehch** [trentm/node-bunyan#436]
It would be great to have possibility sometimes to turn off logging? for example, when testing application (to prevent logging to console when it is not needed).
For example in node.js:

```js
if(process.env.NODE_ENV === 'test') {
    log = bunyan.createLogger({
        mute: true, 
        name: 'Some app'
    });
}
```

or

```js
log.muteOn();

...

log.muteOff();
```

**Comment by Al10s** [comment]
You can choose the log level you want to actually log in the logger's streams
```javascript
if (process.env.NODE_ENV === 'test') {
    log = bunyan.createLogger({
        name: 'Some app',
        streams: [{
            stream: process.stdout,
            level: 'fatal' // Only logs when the level is fatal or higher
        }]
    });
}
```
I guess it should be enough for your use cases.

If you want to "mute" a chunk of code, you could do something like
```javascript
var oldLog = [];
function muteOn () {
    oldLog.push(log);
    log = bunyan.createLogger({
        name: 'Some app',
        streams: [{
            stream: process.stdout,
            level: 'fatal'
        }]
    });
}
function muteOff () {
    if (oldLog.length) {
        log = oldLog[0];
        oldLog = [];
    }
}

...

muteOn();

...

muteOff();
```

**Comment by trentm** [comment]
Thanks for the answer, @Al10s.

@olehch See also this note about a potential future "off" level above fatal that would be more explicit: https://github.com/trentm/node-bunyan/pull/148#issuecomment-53232979
For now, however, using some number higher than `bunyan.FATAL` should work.
