### ISSUE TITLE
How to enable gzip and rename rotating logfile

### ISSUE THREAD

**Issue by Michael-Hamburger** [trentm/node-bunyan#440]
Hello!

I am using bunyan and loving it so far! 👍 

Now I would like to enable gzip compression on rotated logfiles and rename them according the date the file was rotated.

For example I have a global.log. The period is 1d and it should rotate when the next day starts. When today is the 25 September I want the rotated logfiles named like global.24.09.2016.gzip and so on...

Is this possible?
Thanks!

**Comment by trentm** [comment]
Bunyan's log file rotation doesn't support this. You should check out this alternative: https://github.com/Rcomian/bunyan-rotating-file-stream
