### ISSUE TITLE
bunyan config option 'level' question

### ISSUE THREAD

**Issue by syzh** [trentm/node-bunyan#441]
config option 'level' input number support bit operation ？
sample：
{
  src: true,
  name: 'test',
  streams: [
    {
      level: 20|30,    // support ？
      stream: process.stdout 
    },
  ]
}

**Comment by springuper** [comment]
No. You can see how `level` take effects here:

```js
var level = rec.level;
for (i = 0; i < this.streams.length; i++) {
    var s = this.streams[i];
    if (s.level <= level) {
        xxx('writing log rec "%s" to "%s" stream (%d <= %d): %j',
            rec.msg, s.type, s.level, level, rec);
        s.stream.write(s.raw ? rec : str);
    }
};
```
https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L935

**Comment by trentm** [comment]
@syzh Perhaps this note at https://github.com/trentm/node-bunyan/#levels will help clarify:

> Setting a logger instance (or one of its streams) to a particular level implies that all log records
> **at that level and above** are logged. E.g. a logger set to level "info" will log records at
> level info and above (warn, error, fatal).

Setting your logger level to `"info"` (or `30`) will enable logging at the debug and trace levels too.
