### ISSUE TITLE
modern-syslog

### ISSUE THREAD

**Issue by atis--** [trentm/node-bunyan#453]
Hi!

I was wondering what are your thoughts on pointing prospective syslog (via bunyan) users to the [`modern-syslog`](https://github.com/strongloop/modern-syslog) library made by StrongLoop?

Recent build problems with the [node-bunyan-syslog](https://github.com/mcavage/node-bunyan-syslog) library (the only linked syslog solution currently) prompted me to look at other things.

What's interesting is that, according to `modern-syslog` README, the `<syslog.h>` calls may block, and so cause a slowdown under load. They work around this by using [AsyncWorker](https://github.com/nodejs/nan) utilities.

Since `modern-syslog` also provides a stream interface, using it with bunyan is dead simple:

```
const bunyan = require('bunyan');
const syslog = require('modern-syslog');

const log = bunyan.createLogger({
    name: 'myapp',
    stream: syslog.Stream(syslog.LOG_WARNING, syslog.LOG_USER),
    level: 'warn'
});

log.warn({ your: 'data' }, 'Hello, world!');
```

**Comment by trentm** [comment]
@atis-- I've moved the "third-party streams" content to a wiki page so it can be more easily edited by others (I'm often a bottleneck). I'd love if you could add a link to that syslog module here: https://github.com/trentm/node-bunyan/wiki/Awesome-Bunyan and then perhaps also a link to a new wiki page with the above content showing how to use it with Bunyan (or even just a link back to this issue).

**Comment by atis--** [comment]
Ok!
