### ISSUE TITLE
Custom fields always part of a log message

### ISSUE THREAD

**Issue by Ankan-Fraedom** [trentm/node-bunyan#457]
Hi there, using this awesome logging  framework, so thanks a lot for creating and maintaining. Just wondering is it possible to add a custom filed in bunyan which will always appear no matter what I log. Like a requestId appearing always in the log message like a Pid, date etc. would be awesome. Please let me know. Cheers.

**Comment by trentm** [comment]
Yes, that is the default behaviour for all fields other than a few special ones. See https://github.com/trentm/node-bunyan/#constructor-api or, for example:

```
var log = bunyan.createLogger({name: 'myapp', requestId: genRequestId});

log.info('hi'); // This log record will have 'name' and 'requestId' fields per the constructor above.
```

**Comment by tback** [comment]
Is this limited to pure javascript? In typescript it seems I can pass custom strings only. I assume `genRequestId` in your example is a function, right? in @types/bunyan `custom` is an array of strings.

```
import bunyan from 'bunyan';
const genRequestId = () => {return 'an-id'}

const logger = bunyan.createLogger({name: 'app', requestId: genRequestId
});
logger.info('hi')
```
logs this:
```
{"name":"app","hostname":"xxxx.local","pid":19383,"level":30,"msg":"get /","time":"2021-08-05T14:58:44.999Z","v":0}
```
(Notice the request id is missing).
