### ISSUE TITLE
Log event never fires

### ISSUE THREAD

**Issue by DaAwesomeP** [trentm/node-bunyan#459]
I use Bunyan to safely catch all of my errors in my app with `log.error`. However, I need to catch them in tests too. I want to make it so that whenever there is a `error` or `fatal` message it will emit `console.error()`, which Mocha will catch. However, `log.on()` never seems to fire.

```js
let log = bunyan.createLogger({
  name: 'myapp',
  stream: process.stdout,
  level: '10000'  // This is what it's set to during tests to hide log output, but setting it to 'trace' doesn't help with the issue
})
log.req = log.child({ // There are at least 5 log children across the app
  component: 'req',
  level: 'trace',
  serializers: bunyan.stdSerializers
})

if (process.env.NODE_ENV === 'test') {
  log.warn('running in test environment') // This confirms that the app knows that it is running a test, and I know that this works
  let handleError = (err, stream) => {  // As far as I can tell, this never runs
    console.error(err)
  }
  log.on('error', handleError)
  log.on('fatal', handleError)
}
```

**Comment by trentm** [comment]
There is no `log.on` facility in bunyan.

Perhaps this woudl work:

```
if (process.env.NODE_ENV === 'test') {
    log.addStream({
        stream: process.stderr,
        level: 'error'
    });
}
```

Please reopen if I misunderstood your Q.

**Comment by DaAwesomeP** [comment]
Thanks for your swift reply.
> There is no log.on facility in bunyan.

This method is described here: https://github.com/trentm/node-bunyan#stream-errors

I'm trying to make it so that whenever I use `log.error()` or `log.fatal()`, I can use my own function to handle it. I noticed that using `console.error()` with errors will trigger Mocha to fail a test. Mocha doesn't care about Bunayn's JSON logging.

**Comment by DaAwesomeP** [comment]
Your provided example sort of worked. It properly outputed to `stderr`, but it was formatted to the standard Bunyan JSON format. Is there a way to have it output the raw error as if using `console.error()`?

**Comment by trentm** [comment]
That is for a stream error, which is separate from the log levels 'error', 'fatal', 'warn', etc.
E.g. it is for a case where a bunyan file stream writing to, say, /var/log/app.log, gets an IO error or something.

**Comment by trentm** [comment]
To get it to `console.error(err)` or similar you'd want to write your own stream. See this example: https://github.com/trentm/node-bunyan/blob/master/examples/raw-stream.js
