### ISSUE TITLE
Bunyan's `safeCycles` is too slow when logging large objects

### ISSUE THREAD

**Issue by trentm** [trentm/node-bunyan#474]
Bunyan logging of large objects is SLOOOOOW.

We did some digging on timing JSON.parse/serialize of large JSON objects such as
you get with a Docker image config/manifest with a large number of exposed
ports. The test files are here in Manta:

```
[trent.mick@us-east /trent.mick/public/bugs/bunyan472]$ ls -al
   object  trent.mick     6465820  2017-01-25T22:39:08.937Z  784cbf789635.blob
   object  trent.mick      277900  2017-01-25T22:39:16.098Z  bigimg.json
   object  trent.mick        1354  2017-01-25T22:40:00.839Z  timebigjson.js
```

Which you can download via:
- https://us-east.manta.joyent.com/trent.mick/public/bugs/bunyan472/784cbf789635.blob
- https://us-east.manta.joyent.com/trent.mick/public/bugs/bunyan472/bigimg.json
- https://us-east.manta.joyent.com/trent.mick/public/bugs/bunyan472/timebigjson.js

Timings on my Mac are as follows:

{code}
$ node timebigjson.js
Time JSON.parse, JSON.stringify, and bunyan logging for large JSON files:
--
process.memoryUsage: { rss: 21188608, heapTotal: 9385584, heapUsed: 5505584 }
path: ./bigimg.json
size: 277900 bytes
JSON.parse(str): 7.17ms per iteration
JSON.stringify(parsed): 4.29ms per iteration
log.info({img: parsed}, ...): 81.3ms per iteration
process.memoryUsage: { rss: 69328896, heapTotal: 51694960, heapUsed: 25299648 }
--
process.memoryUsage: { rss: 69345280, heapTotal: 51694960, heapUsed: 25363616 }
path: ./784cbf789635.blob
size: 6465820 bytes
JSON.parse(str): 203.29ms per iteration
JSON.stringify(parsed): 161.76ms per iteration
log.info({img: parsed}, ...): 31804.666666666668ms per iteration
process.memoryUsage: { rss: 594235392, heapTotal: 484728176, heapUsed: 438764464 }
{code}

What this shows is that `log.info` is ridiculously slow (30s compared to a
vanilla JSON.stringify's 161ms) for large objects. The reason is that Bunyan's
creation of a log record uses a `replacer` function to `JSON.stringify` to avoid
object cycles
(https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L912):

{code}
function safeCycles() {
    var seen = [];
    return function (key, val) {
        if (!val || typeof (val) !== 'object') {
            return val;
        }
        if (seen.indexOf(val) !== -1) {
            return '[Circular]';
        }
        seen.push(val);
        return val;
    };
}

// ...
str = JSON.stringify(rec, safeCycles()) + '\n';
{code}

That 'safeCycles' has abysmal perf for lots of objects because it is doing
O(N) `seen.indexOf` lookup for each object.

---

Let's try to do better:

```javascript
// A JSON stringifier that handles cycles safely.
// Usage: JSON.stringify(obj, safeCycles())
var s = Symbol('bunyan_cycle_id')
var ctr = 0;
function safeCyclesSymbol() {
    ctr++;

    return function (key, val) {
        if (!val || typeof (val) !== 'object') {
            return val;
        }
        if (val[s] === ctr) {
            return '[Circular]';
        }
        val[s] = ctr;
        return val;
    }
}

function safeCyclesSet() {
    var seen = new Set();
    return function (key, val) {
        if (!val || typeof (val) !== 'object') {
            return val;
        }
        if (seen.has(val)) {
            return '[Circular]';
        }
        seen.add(val);
        return val;
    };
}

function safeCyclesArray() {
    var seen = [];
    return function (key, val) {
        if (!val || typeof (val) !== 'object') {
            return val;
        }
        if (seen.indexOf(val) !== -1) {
            return '[Circular]';
        }
        seen.push(val);
        return val;
    };
}

var safeCycles = safeCyclesSymbol;
```

Timings on my Mac for the 6.4MB "./784cbf789635.blob" with each of these
safeCycles implementations, and without a replacer function are as follows:

```
# safeCyclesArray
log.info({img: parsed}, ...): 31790.666666666668ms per iteration

# safeCyclesSet
log.info({img: parsed}, ...): 994.6666666666666ms per iteration

# safeCyclesSymbol
log.info({img: parsed}, ...): 864ms per iteration

# no safeCycles replacer function
log.info({img: parsed}, ...): 192.66666666666666ms per iteration
```

There is an obvious win here. The Q is what impl to use and whether to make
that configurable. Some considerations:

- `Symbol` and `Set` appeared only in node 0.12, so to keep node 0.10 compat
  we'll have to have the fallback implementation.
- `Set` is a cleaner implementation, but is ~10% slower than the Symbol impl.
- The `ctr` used for the `Symbol` *can* overflow at `Number.MAX_SAFE_INTEGER`
  (9007199254740991), such that an attempt to log the same object over
  9 quadrillion times will result in it being logged as '[Circular]'.
  Given that a minimal bunyan log line:
        {"name":"a","hostname":"b","pid":3,"level":30,"msg":"d","time":"2016-05-17T23:31:43.621Z","v":0}
  is about 96 characters. That is about 864PiB of data, so I think there will
  be other problems first.
- *Not* using safeCycles is quite a bit faster (at least for large objects).
  That argues for potentially giving the user the ability to not use it.
  I.e. the user takes responsibility that they won't pass objects with cycles
  to Bunyan loggers.

TODO: Put together a PR for change that exposes an option to
`bunyan.createLogger` for which safeCycles impl to use. It is an error to
request the Set or Symbol one if using node 0.10 where they aren't available.

**Comment by twhiteman** [comment]
I had another thought for speeding up the safeCycles code path.

Since `JSON.stringify(circObj)` will throw an exception in the case of a cycle (TypeError: Converting circular structure to JSON), what about try/catching that call and then only then do you try to use the safe cycles approach.

My thoughts are that most of the time (i.e. the common case) bunyan would be using objects that don't contain a cycle, so you'd get the best performance for most cases.

This is the comparison of timebigjson.js when using this approach:

## BEFORE (using new safeCycles Set approach)
```
Time JSON.parse, JSON.stringify, and bunyan logging for large JSON files:
--
process.memoryUsage: { rss: 25726976, heapTotal: 9472608, heapUsed: 5671464 }
path: ./data/261fc5a46127.blob
size: 277900 bytes
JSON.parse(str): 7.9ms per iteration
JSON.stringify(parsed): 5.3ms per iteration
log.info({img: parsed}, ...): 26.666666666666668ms per iteration
process.memoryUsage: { rss: 70680576, heapTotal: 51781984, heapUsed: 18450832 }
--
process.memoryUsage: { rss: 70684672, heapTotal: 51781984, heapUsed: 18472368 }
path: ./data/784cbf789635.blob
size: 6465820 bytes
JSON.parse(str): 190.1ms per iteration
JSON.stringify(parsed): 153.7ms per iteration
log.info({img: parsed}, ...): 785ms per iteration
process.memoryUsage: { rss: 252297216, heapTotal: 190301280, heapUsed: 154075080 }
```

## AFTER (using straight JSON.stringify in a try/catch)
```
node timebigjson.js
Time JSON.parse, JSON.stringify, and bunyan logging for large JSON files:
--
process.memoryUsage: { rss: 25718784, heapTotal: 9472608, heapUsed: 5673432 }
path: ./data/261fc5a46127.blob
size: 277900 bytes
JSON.parse(str): 7.1ms per iteration
JSON.stringify(parsed): 5.4ms per iteration
log.info({img: parsed}, ...): 5.333333333333333ms per iteration
process.memoryUsage: { rss: 59273216, heapTotal: 51781984, heapUsed: 16793952 }
--
process.memoryUsage: { rss: 59273216, heapTotal: 51781984, heapUsed: 16815344 }
path: ./data/784cbf789635.blob
size: 6465820 bytes
JSON.parse(str): 186.2ms per iteration
JSON.stringify(parsed): 159.5ms per iteration
log.info({img: parsed}, ...): 201ms per iteration
process.memoryUsage: { rss: 543535104, heapTotal: 480700000, heapUsed: 451291528 }
```

Which is approximately 4 times faster.
