### ISSUE TITLE
docs say level() produces a string like INFO but it produces a number like 30

### ISSUE THREAD

**Issue by jcollum** [trentm/node-bunyan#476]
Docs: 

```
log.level() -> INFO   // gets current level (lowest level of all streams)
```

My code: 

```
self.logger.warn('Log level is ' + self.logger.level() + '.');
```

Output: 

```
21:30:05.447Z  WARN ukulele: Log level is 30.
```

**Comment by ChrRaz** [comment]
`INFO` in the doc is referring to the [INFO](https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L258) variable declared in the main script, not the string `"INFO"`.

**Comment by Gopaljeepurwar** [comment]
Can we print log level into string format ?
 Ex:
{"name":"test-app","hostname":"test.local","pid":55973,**"level":"INFO"**,"time":"2017-05-08T09:41:36.215Z","v":0}

**Comment by jcollum** [comment]
I don't have the code handy but there is a way to turn an integer into a log-level-describing string in bunyan's codebase. Something like `levelToString(int)`.

**Comment by Gopaljeepurwar** [comment]
@jcollum  Can you please share the exact code ?

**Comment by jcollum** [comment]
Previous job. I no longer have access. But I'm certain it can be done.
