### ISSUE TITLE
How to connect two or more Bunyan loggers?

### ISSUE THREAD

**Issue by thanpolas** [trentm/node-bunyan#477]
Hello, I am authoring a library for npm and thought I'd use Bunyan for logging.

Is there a way to connect two Bunyan loggers together?

The idea is that I will expose the Bunyan logger for the consuming service and supposedly somehow, if they also use Bunyan, would be able to connect the library's logger with their service logger as the parent. 

I couldn't find any writable stream on the Bunyan logger to perform a link like:

```js
    libraryLogger.addStream({
      type: 'stream',
      stream: serviceLogger,
      closeOnExit: false,
      level: 'trace',
    });
```

Something like that would be really convenient.

For now I'll resort to having logs being emitted as events from the library.

**Comment by trentm** [comment]
@thanpolas My common setup is to write libraries to take a Bunyan logger instance. Then the app create the logger instance and passes that to the library. For example, if I have an app using the [restify](http://restify.com/) library, I might ahve code like this:

```
...
    this.log = bunyan.createLogger({...});
    var server = this.server = restify.createServer({
        name: this.serverName,
        log: this.log,
```

Then the library (restify in my example) would use that passed in logger. The library can either be written to create its own Bunyan logger if not given one, or just not log at all if no logger is passed in.

I suppose you could try to call `addStream` on the library's logger with each of the streams on your app's logger. Something like:

```
myAppLog.streams.forEach(function (s) {
    libraryLogger.addStream({
        type: 'stream', stream: s.stream, closeOnExit: false, level: 'trace'
    });
});
```

**Comment by thanpolas** [comment]
accepting a logger through dependency injection makes a lot of assumptions. Not all codebases  use the `trace`, debug`, `info`, `warn`, `error` system of hierarchy.

I understand how this is the pragmatic solution today but I would really love to see this composability in loggers at large. I've looked at all the options today and none offers the option to mix different input streams together.
