### ISSUE TITLE
"ReferenceError: Set is not defined" in older versions of node

### ISSUE THREAD

**Issue by JustinMcConnell** [trentm/node-bunyan#484]
It looks like the latest 1.8.6 release is throwing errors in older versions of node/V8 that do not support the Set object.
```
➜  bunyan node test.js 

/Users/justinmcconnell/Documents/code/bunyan/node_modules/bunyan/lib/bunyan.js:1200
var safeCycles = Set ? safeCyclesSet : safeCyclesArray;
                 ^
ReferenceError: Set is not defined
    at Object.<anonymous> (/Users/justinmcconnell/Documents/code/bunyan/node_modules/bunyan/lib/bunyan.js:1200:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/justinmcconnell/Documents/code/bunyan/test.js:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

I believe this could be simply solved by changing line 1200 to:
`var safeCycles = typeof Set !== 'undefined' ? safeCyclesSet : safeCyclesArray;`

My node version:
```
➜  bunyan node -v
v0.10.37
```

package.json:
```
{
  "dependencies": {
    "bunyan": "1.8.5"
  }
}
```

test.js:
```
'use strict';

var bunyan = require('bunyan');
console.log('required');
```

**Comment by JustinMcConnell** [comment]
I submitted [this PR](https://github.com/trentm/node-bunyan/pull/485).

**Comment by trentm** [comment]
bunyan@1.8.7 published with this fix. @JustinMcConnell  Thanks!

**Comment by JustinMcConnell** [comment]
Hey Trent.  Thanks for the quick turnaround!  ❤️  open source.

**Comment by JustinMcConnell** [comment]
Interesting, it's still broken when I get the module from npm.

Here's the line in the github repo:
`var safeCycles = typeof (Set !== 'undefined') ? safeCyclesSet : safeCyclesArray;`

and here is what I get when I `npm install bunyan`:
`var safeCycles = typeof (Set !== 'undefined') ? safeCyclesSet : safeCyclesArray;`

Somehow it got modified.

**Comment by trentm** [comment]
Yah, I screwed up. Fixed and published as bunyan@1.8.8. Sorry about that.

**Comment by cyrfer** [comment]
`var safeCycles = typeof (Set) !== 'undefined' ? safeCyclesSet : safeCyclesArray;`

**Comment by trentm** [comment]
@cyrfer Really?  Here is what I see:

```
$ node
> process.version
'v0.10.48'
> typeof (Set)
'undefined'
```

**Comment by JustinMcConnell** [comment]
Works for me in 0.10.37

```
$ node
> process.version
'v0.10.37'
> typeof (Set)
'undefined'
```

**Comment by cyrfer** [comment]
I retract my statement. I'm not sure how I got that error. After another install I see it working in 0.10.26.
