### ISSUE TITLE
CLI reader does not output single quotes in error stack traces

### ISSUE THREAD

**Issue by acarstoiu** [trentm/node-bunyan#486]
I was reading some log containing a stack trace through the command line tool and I noticed that the error messages are not rendered accurately.
If a text contains single quotes, like
```
"stack":"Could not read property 'abcdef'."
```
the `bunyan` executable will output
```
Could not read property abcdef.
```
I don't see why do you strip the quotes. I'm using the quotes as mark-up for names that are not to be confused with actual words.

**Comment by trentm** [comment]
Do you have the original (or an example) raw bunyan log record with which
we could reproduce that?

-- Trent

**Comment by acarstoiu** [comment]
Sorry, must have been an older version of _bunyan_.
