### ISSUE TITLE
jsonPayload in GAE

### ISSUE THREAD

**Issue by walshe** [trentm/node-bunyan#507]
would you have any idea where i am going wrong here ?

https://stackoverflow.com/questions/44268932/bunyan-not-putting-data-in-jsonpayload-field-in-google-app-engine

**Comment by trentm** [comment]
I'm sorry I can't help. I don't know the GAE environment. I imagine it has something to do with the Bunyan output (to the default process.stdout stream in your createLogger example) being a JSON *string*. I'm guessing that the GAE environment is just capturing each line of string output on stdout and adding that to the "textPayload".
