### ISSUE TITLE
rotating-file file name

### ISSUE THREAD

**Issue by 39Er** [trentm/node-bunyan#508]
How to customize the log file name ? 
There are :
```
/var/log/foo.log.0     # yesterday
/var/log/foo.log.1     # 1 day ago
/var/log/foo.log.2     # 2 days ago
```
but I expect :

```
/var/log/foo.log.20170607     # yesterday
/var/log/foo.log.20170606    # 1 day ago
/var/log/foo.log.20170605    # 2 days ago
```

**Comment by 39Er** [comment]
I find a way to resolve

**Comment by Ma63d** [comment]
@39Er  Could you please show your solution? Thanks!

**Comment by 39Er** [comment]
@Ma63d  我自定义了一个 stream，周期为一天，详见 https://github.com/39Er/bunyan-rotate-file-stream

**Comment by Ma63d** [comment]
@39Er 啊哈，看到了。你自己实现了 rotate 逻辑。
多谢了！
