### ISSUE TITLE
turn colors off

### ISSUE THREAD

**Issue by jensengar** [trentm/node-bunyan#513]
I'm running this in elastic beanstalk and the color codes are showing up in the logs and making a mess of things. Is there a way to disable colors? This is an example of what I'm seeing in the logs:
`[39m[90m[2017-06-16T01:52:10.568Z][39m [31mERROR[39m: routeErrorHandler/13416 on ipaddress:
[90m  [36mError: ER_BAD_FIELD_ERROR: Unknown column 'au.recipientId' in 'where clause'`

**Comment by ORESoftware** [comment]
I think there is probably an env variable you can set for chalk/colors to turn off colors

**Comment by mrchief** [comment]
Its `FORCE_COLOR=0` for chalk module but that doesn't help. It still emits those color sequences.

**Comment by trentm** [comment]
```
$ bunyan -h
...
Output options:
  ...
  --no-color    Force no coloring (e.g. terminal doesn't support it)
  ...

Environment Variables:
  BUNYAN_NO_COLOR    Set to a non-empty value to force no output
                     coloring. See "--no-color".
  ...
```

Cheers.

**Comment by mrchief** [comment]
@trentm I didn't realize this issue was for the CLI tool. :)

**Comment by trentm** [comment]
Ah, yah. At least *currently*, it is only the `bunyan` CLI that does anything with ANSI codes. The bunyan *module* is all about simple JSON output.
