### ISSUE TITLE
log.error({ msg: 'Hello' }) logs no message

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [trentm/node-bunyan#515]
Hi :)

I'm trying to figure out why I cannot specify the "main" message (such as when just doing `log.error('Hello')` when I pass in an object to be logged.

No matter how complex or simple the object I'm passing in is, the `.msg` property always comes out blank if I pass it in myself. When piping log output through bunyan, the usually cyan message is just not there, when logging raw, I can see a `"msg": ""` in the logged object.

If I pass in an Error, it copies the `.message` property from it to `.msg`.

If I do something like `log.warn({ msg: 'Uncaught ApiError — Fix yo code!', horses: true, err: err })`, it copies the nested `.err.message` property to `.msg`. What gives? Am I being retarded here, or is something broken?

Cheers :)
Daniel

**Comment by DanielSmedegaardBuus** [comment]
Okay, it seems I **am** retarded, as upon inspecting the `mkRecord` function I discovered I just have to pass the message and arguments to `util.format` as arguments **after** the object.

A bit confusing though, as I didn't discover this by reading the README, where it even states that `.msg` is _required_, which leads you to believe that you can just pass it in...

Well, anyway, issue closed :) Cheers!

**Comment by curusarn** [comment]
Hi @trentm,

Is this really the intended behavior?
Is there any benefit to ignoring 'msg' field and requiring it to be passed separately?
The resulting behaviour seems quite confusing to me.

What do you think about this approach: https://github.com/trentm/node-bunyan/pull/629/files
Would you be open to consider a fix like this?

I'm sorry about commenting on an older issue. 🙏
Thanks in advance.
