### ISSUE TITLE
"msg" field is empty

### ISSUE THREAD

**Issue by DanielHreben** [trentm/node-bunyan#517]
In some reason this code
```javascript
const bunyan = require('bunyan')
const logger = bunyan.createLogger({name: 'myapp'})
logger.warn({msg: 'test'})
```

will output log entry with empty "msg" field:
```json
{"name":"myapp","hostname":"Daniels-MacBook-Air.local","pid":32837,"level":40,"msg":"","time":"2017-07-03T21:41:43.325Z","v":0}
```

**Comment by ORESoftware** [comment]
msg might be a predefined field? check the README

**Comment by ORESoftware** [comment]
when you close a question @DanielHreben it's good etiquette to explain what the problem/answer was so that you could potentially help others lol.

**Comment by DanielHreben** [comment]
Well, I will be happy to explain that, but I don't understand real reasons, from your answer I only realize that's not a bug, since msg is a predefined field. 
"err" is also predefined field, but it works that way:
```
logger.error({err: new Error()}) // "err" field will be present, everything is ok
```
