### ISSUE TITLE
Cannot find module './build/Release/DTraceProviderBindings

### ISSUE THREAD

**Issue by SergeyJyravlev** [trentm/node-bunyan#532]
dtrace-provider@0.8.5 install /Users/sergei/projects/app/node_modules/bunyan/node_modules/dtrace-provider

Building dtrace-provider failed with exit code 1 and signal 0
re-run install with environment variable V set to see the build output

node 6.10.3
npm 5.3.0
macOS 10.12.6
Please help

**Comment by hsingh23** [comment]
I'm having the same problem

**Comment by tonylukasavage** [comment]
same here on node 8.4 and 8.5, bunyan 1.8.1

**Comment by timrs2998** [comment]
Same problem.

Do we need dtrace-provider as an optional dependency? Although npm can ignore optional dependencies, the intent of optional deps is to allow install of the dependency to fail silently. Yarn has issues ignoring optional dependencies.

**Comment by dmunozgaete** [comment]
same here =(

**Comment by arturnt** [comment]
Please fix!

**Comment by melloc** [comment]
As of `dtrace-provider@0.8.6`, this message will no longer be printed to stderr at runtime, and the stub implementation will be used instead. If you want to use `bunyan -p` or write your own DTrace scripts to process Bunyan logs, then you can set `NODE_DTRACE_PROVIDER_REQUIRE=hard` during installation to force the build to fail and see why it failed. For example:

```
$ NODE_DTRACE_PROVIDER_REQUIRE=hard npm install
```

There is a list of common failure reasons in [dtrace-provider's README](https://github.com/chrisa/node-dtrace-provider/blob/master/README.md#platform-support). Please take a look there first before opening any bugs.
