### ISSUE TITLE
How to use with nodemon?

### ISSUE THREAD

**Issue by mywebstuff** [trentm/node-bunyan#542]
I'm trying to run my application with nodemon and pipe the output through bunyan cli. For example:
```
nodemon .\backend\main.js --watch .\backend |bunyan
```

However this doesn't show any logs, I'm not even sure my application has started. Any ideas on what's wrong?

**Comment by voxpelli** [comment]
`nodemon . | bunyan` works fine for me – I've used it for a long while

**Comment by mywebstuff** [comment]
So I've found out that this is not working on Powershell (Windows), but works on cmd. Interesting.

**Comment by mrchief** [comment]
Powershell pipes are different than other shell pipes - they expect objects and not character data.

**Comment by mywebstuff** [comment]
Thank you!
