### ISSUE TITLE
Bunyan does not print to Stdout when debugging in VSCode

### ISSUE THREAD

**Issue by honestserpent** [trentm/node-bunyan#545]
When I debug my application with Visual Studio Code, bunyan does not print anything in the debugging console.

Logging on files works fine.

**Steps to reproduce:**
Create a project in VSCode and lunch it in debug within VSCode (F5)

```
'use strict'

var logger = require('bunyan').createLogger({
  name: 'mylogger',
  level: 'debug'
})

console.log('before bunyan logs')

logger.debug('debug')
logger.info('info')
logger.warn('warn')
logger.error('error')

console.log('after bunyan logs')
```

**Comment by sppatel** [comment]
What version of node?

**Comment by honestserpent** [comment]
Yeah sorry, I didn't put it. So, I have tested with **Node v8.8.1**.
Non-debug mode works as expected, printing: 

```
{"name":"mylogger","hostname":"WK-025","pid":7020,"level":20,"msg":"debug","time":"2018-02-13T07:50:01.222Z","v":0}
{"name":"mylogger","hostname":"WK-025","pid":7020,"level":30,"msg":"info","time":"2018-02-13T07:50:01.226Z","v":0}
{"name":"mylogger","hostname":"WK-025","pid":7020,"level":40,"msg":"warn","time":"2018-02-13T07:50:01.227Z","v":0}
{"name":"mylogger","hostname":"WK-025","pid":7020,"level":50,"msg":"error","time":"2018-02-13T07:50:01.228Z","v":0}
```

**Comment by sppatel** [comment]
Add the following to your launch configuration..

`            "outputCapture": "std",
`

**Comment by honestserpent** [comment]
Perfect, that solved the problem. Thank you.

**Comment by pookdeveloper** [comment]
@sppatel dosen't work for me, buyan dosen't have this property
![image](https://user-images.githubusercontent.com/3384734/64639539-51e06c80-d408-11e9-9b5d-87c7b3330e37.png)
