### ISSUE TITLE
Stop depending on dtrace provider

### ISSUE THREAD

**Issue by domenic** [trentm/node-bunyan#60]
We were using this package great on Windows and Linux in the 0.10 timeframe; now we can't install it.

**Comment by mbana** [comment]
has this been fixed?

**Comment by Floby** [comment]
nope.

**Comment by bruce-lindsay** [comment]
I found this to be helpful after being stuck on this problem for a bit.
 https://www.npmjs.com/package/bunyan-sfdx-no-dtrace
