### ISSUE TITLE
How to "nest" streams (to change the raw object before logging)

### ISSUE THREAD

**Issue by petermorlion** [trentm/node-bunyan#623]
I'm using bunyan to log data that sometimes contains personally identifiable information (PII). For legal reasons, we need to remove this. I can do this easily enough, but I'd like to avoid having to do this on every call.

So, I don't want this:

```
logger.info(removeSecrets(data), "Something happened");
```

This assumes no developer will ever forget. I was thinking about creating a stream that receives the raw object, removes any PII, and then passes it on to the default stream that Bunyan provides.

I can't just pass the raw object to `process.stdout` because I see Bunyan still does quite some things with the raw object.

Can I do this easily? Can I "nest" streams?

**Comment by techieshark** [comment]
@petermorlion did you come to a solution?

I see Bunyan docs seem to suggest always logging an object and keying your fields in a standard manner. For example:

```
logger.info({ req: req, pii: somePrivateData }) 
```

Assuming that would work in your case, I imaging you could use Bunyan's "serializers". 
```
const bunyanLogger = bunyan.createLogger({ ... })
bunyanLogger.addSerializers({
    pii: (data) => removeSecrets(data)
});
```

**Comment by petermorlion** [comment]
My apologies, I totally forgot about this issue. Yes, I did find a solution. The "problem" with your proposed solution (IMO) is that it still assumes the developer won't forget to put all PII in the `pii` field.

This is what I came up with. When creating a logger, we can use a custom stream:

```
const logger = bunyan.createLogger({
    streams: [
        {
            type: "raw",
            stream: new SecretHidingStream(process.stdout)
        }
    ]
});
```

And this is what our `SecretHidingStream` looks like (we're using Typescript by the way):

```
import safeJsonStringify = require("safe-json-stringify");
import { Stream } from "stream";
import { hideSecrets } from "./hideSecrets";

export class SecretHidingStream extends Stream.Writable {
    private nestedStream: NodeJS.WritableStream;

    public constructor(nestedStream?: NodeJS.WritableStream) {
        super({ objectMode: true });
        this.nestedStream = nestedStream || process.stdout;
    }

    public _write(record: any, encoding?: string, cb?: (error: Error | null | undefined) => void): void {
        const obfuscatedRecord = hideSecrets(record);
        const s = safeJsonStringify(obfuscatedRecord) + "\n";
        this.nestedStream.write(s, encoding, (e: any) => {
            if (!e) {
                return;
            }
            console.error(e);
        });

        cb(null);
    }
}
```

The `hideSecrets` function is fairly custom to us. We use [traverse](https://www.npmjs.com/package/traverse) to run through the object and the child objects to obfuscate any PII fields. Basically, if a field key matches a known list of PII fields, we obfuscate. It's a little more complex than that, but that's basically it.

We put all this logic in a private npm package so that this all happens when the developer calls the `createLogger` method from our package, i.e. the streams are all created for them.

**Comment by techieshark** [comment]
Thanks much for sharing that strategy & code, @petermorlion!
