### ISSUE TITLE
once used to `log.xxx(err)` it isn't obvious how to add another field: improve docs

### ISSUE THREAD

**Issue by trentm** [trentm/node-bunyan#7]
```
    log.info({
      err: error,
      url: req.url,
      params: req.params
    });
```

plus requiring an `err` serializer.   That's a big leap. Need to doc that better.

**Comment by Cactusbone** [comment]
:+1:

**Comment by jazzzz** [comment]
:+1: I will try to implement it!

**Comment by jazzzz** [comment]
See PR #290 to add additional fields with an error.

**Comment by trentm** [comment]
I've tried to improve the docs for this in the above commit.

@jazzzz Thanks for the PR work, but I don't want to take that API change.
