### ISSUE TITLE
Getting the stack (src attribute)

### ISSUE THREAD

**Issue by gagle** [trentm/node-bunyan#72]
If we set `src` to true the third (`caller = stack[2]`) element in the stack is returned, but we can have a wrapper that uses bunyan. I have a log function that calls your bunyan log function, so the third element is not my log call, it's yours, I have to set:

``` javascript
Error.stackTraceLimit = 4;
...
caller = stack[3];
```

You're wondering why I have a wrapper. Well, that's because I need to use the same logger on different modules, so first I need to initialize it creating a logger. I have to cache the bunyan log inside my wrapper.

Your could add an extra attribute in the `createLogger`, `stack`. If src is true read the stack attribute (default 2).

Solution:

line 444:

``` javascript
this.stack = "stack" in options ? options.stack : 2;
```

line 458:

``` javascript
delete fields.stack;
```

line 774:

``` javascript
rec.src = getCaller3Info(log.stack)
```

getCaller3Info:

``` javascript
function getCaller3Info(n) {
  ...
  Error.stackTraceLimit = n + 1;
  ...
  var caller = stack[n];
  ...
}
```

</hr>

Usage:

``` javascript
bunyan.createLogger ({
  ...,
  src: true,
  stack: 3
})

bunyan.createLogger ({
  ...,
  src: true //default stack, 2
})
```

**Comment by jinwolf** [comment]
Hi any updates on this, this change will be useful

**Comment by nathHy** [comment]
Any updates on this one? I've run into the same issue trying to use a wrapper around my logger
